<?php
/**
 * TrendsQuoteSandboxResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * TrendsQuoteSandboxResponse Class Doc Comment
 *
 * @category Class
 * @description Mock pricing response. Shape differs between single (1-leg) and parlay (2+ legs); parlay responses additionally carry top-level combined odds and is_combinable / parlay_failure_reason.
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrendsQuoteSandboxResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'trends_QuoteSandboxResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'american_odds_value' => 'string',
        'button_payload' => 'string',
        'decimal_odds_value' => 'float',
        'event_betting_market_position_maps' => 'object[]',
        'flow_id' => 'int',
        'flow_type' => 'string',
        'fractional_odds_value' => 'string',
        'is_combinable' => 'bool',
        'odds_implied_probability' => 'float',
        'parlay_failure_reason' => 'string',
        'payout_multiplier' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'american_odds_value' => null,
        'button_payload' => null,
        'decimal_odds_value' => null,
        'event_betting_market_position_maps' => null,
        'flow_id' => 'int64',
        'flow_type' => null,
        'fractional_odds_value' => null,
        'is_combinable' => null,
        'odds_implied_probability' => null,
        'parlay_failure_reason' => null,
        'payout_multiplier' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'american_odds_value' => true,
        'button_payload' => true,
        'decimal_odds_value' => true,
        'event_betting_market_position_maps' => false,
        'flow_id' => false,
        'flow_type' => false,
        'fractional_odds_value' => true,
        'is_combinable' => false,
        'odds_implied_probability' => true,
        'parlay_failure_reason' => true,
        'payout_multiplier' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'american_odds_value' => 'american_odds_value',
        'button_payload' => 'button_payload',
        'decimal_odds_value' => 'decimal_odds_value',
        'event_betting_market_position_maps' => 'event_betting_market_position_maps',
        'flow_id' => 'flow_id',
        'flow_type' => 'flow_type',
        'fractional_odds_value' => 'fractional_odds_value',
        'is_combinable' => 'is_combinable',
        'odds_implied_probability' => 'odds_implied_probability',
        'parlay_failure_reason' => 'parlay_failure_reason',
        'payout_multiplier' => 'payout_multiplier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'american_odds_value' => 'setAmericanOddsValue',
        'button_payload' => 'setButtonPayload',
        'decimal_odds_value' => 'setDecimalOddsValue',
        'event_betting_market_position_maps' => 'setEventBettingMarketPositionMaps',
        'flow_id' => 'setFlowId',
        'flow_type' => 'setFlowType',
        'fractional_odds_value' => 'setFractionalOddsValue',
        'is_combinable' => 'setIsCombinable',
        'odds_implied_probability' => 'setOddsImpliedProbability',
        'parlay_failure_reason' => 'setParlayFailureReason',
        'payout_multiplier' => 'setPayoutMultiplier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'american_odds_value' => 'getAmericanOddsValue',
        'button_payload' => 'getButtonPayload',
        'decimal_odds_value' => 'getDecimalOddsValue',
        'event_betting_market_position_maps' => 'getEventBettingMarketPositionMaps',
        'flow_id' => 'getFlowId',
        'flow_type' => 'getFlowType',
        'fractional_odds_value' => 'getFractionalOddsValue',
        'is_combinable' => 'getIsCombinable',
        'odds_implied_probability' => 'getOddsImpliedProbability',
        'parlay_failure_reason' => 'getParlayFailureReason',
        'payout_multiplier' => 'getPayoutMultiplier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PARLAY_FAILURE_REASON_ONE_OR_MORE_LEGS_FAILED = 'one or more legs failed';
    public const PARLAY_FAILURE_REASON_SELECTIONS_ARE_NOT_COMBINABLE = 'selections are not combinable';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getParlayFailureReasonAllowableValues()
    {
        return [
            self::PARLAY_FAILURE_REASON_ONE_OR_MORE_LEGS_FAILED,
            self::PARLAY_FAILURE_REASON_SELECTIONS_ARE_NOT_COMBINABLE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('american_odds_value', $data ?? [], null);
        $this->setIfExists('button_payload', $data ?? [], null);
        $this->setIfExists('decimal_odds_value', $data ?? [], null);
        $this->setIfExists('event_betting_market_position_maps', $data ?? [], null);
        $this->setIfExists('flow_id', $data ?? [], null);
        $this->setIfExists('flow_type', $data ?? [], null);
        $this->setIfExists('fractional_odds_value', $data ?? [], null);
        $this->setIfExists('is_combinable', $data ?? [], null);
        $this->setIfExists('odds_implied_probability', $data ?? [], null);
        $this->setIfExists('parlay_failure_reason', $data ?? [], null);
        $this->setIfExists('payout_multiplier', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['event_betting_market_position_maps'] === null) {
            $invalidProperties[] = "'event_betting_market_position_maps' can't be null";
        }
        if ($this->container['flow_id'] === null) {
            $invalidProperties[] = "'flow_id' can't be null";
        }
        if ($this->container['flow_type'] === null) {
            $invalidProperties[] = "'flow_type' can't be null";
        }
        $allowedValues = $this->getParlayFailureReasonAllowableValues();
        if (!is_null($this->container['parlay_failure_reason']) && !in_array($this->container['parlay_failure_reason'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'parlay_failure_reason', must be one of '%s'",
                $this->container['parlay_failure_reason'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets american_odds_value
     *
     * @return string|null
     */
    public function getAmericanOddsValue()
    {
        return $this->container['american_odds_value'];
    }

    /**
     * Sets american_odds_value
     *
     * @param string|null $american_odds_value Parlay only. Null when uncombinable.
     *
     * @return self
     */
    public function setAmericanOddsValue($american_odds_value)
    {
        if (is_null($american_odds_value)) {
            array_push($this->openAPINullablesSetToNull, 'american_odds_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('american_odds_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['american_odds_value'] = $american_odds_value;

        return $this;
    }

    /**
     * Gets button_payload
     *
     * @return string|null
     */
    public function getButtonPayload()
    {
        return $this->container['button_payload'];
    }

    /**
     * Sets button_payload
     *
     * @param string|null $button_payload Synthetic bet-slip identifier (prefix 'FD-MOCK-'). Null when the result is invalid or the parlay is uncombinable.
     *
     * @return self
     */
    public function setButtonPayload($button_payload)
    {
        if (is_null($button_payload)) {
            array_push($this->openAPINullablesSetToNull, 'button_payload');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('button_payload', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['button_payload'] = $button_payload;

        return $this;
    }

    /**
     * Gets decimal_odds_value
     *
     * @return float|null
     */
    public function getDecimalOddsValue()
    {
        return $this->container['decimal_odds_value'];
    }

    /**
     * Sets decimal_odds_value
     *
     * @param float|null $decimal_odds_value decimal_odds_value
     *
     * @return self
     */
    public function setDecimalOddsValue($decimal_odds_value)
    {
        if (is_null($decimal_odds_value)) {
            array_push($this->openAPINullablesSetToNull, 'decimal_odds_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('decimal_odds_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['decimal_odds_value'] = $decimal_odds_value;

        return $this;
    }

    /**
     * Gets event_betting_market_position_maps
     *
     * @return object[]
     */
    public function getEventBettingMarketPositionMaps()
    {
        return $this->container['event_betting_market_position_maps'];
    }

    /**
     * Sets event_betting_market_position_maps
     *
     * @param object[] $event_betting_market_position_maps event_betting_market_position_maps
     *
     * @return self
     */
    public function setEventBettingMarketPositionMaps($event_betting_market_position_maps)
    {
        if (is_null($event_betting_market_position_maps)) {
            throw new \InvalidArgumentException('non-nullable event_betting_market_position_maps cannot be null');
        }
        $this->container['event_betting_market_position_maps'] = $event_betting_market_position_maps;

        return $this;
    }

    /**
     * Gets flow_id
     *
     * @return int
     */
    public function getFlowId()
    {
        return $this->container['flow_id'];
    }

    /**
     * Sets flow_id
     *
     * @param int $flow_id flow_id
     *
     * @return self
     */
    public function setFlowId($flow_id)
    {
        if (is_null($flow_id)) {
            throw new \InvalidArgumentException('non-nullable flow_id cannot be null');
        }
        $this->container['flow_id'] = $flow_id;

        return $this;
    }

    /**
     * Gets flow_type
     *
     * @return string
     */
    public function getFlowType()
    {
        return $this->container['flow_type'];
    }

    /**
     * Sets flow_type
     *
     * @param string $flow_type flow_type
     *
     * @return self
     */
    public function setFlowType($flow_type)
    {
        if (is_null($flow_type)) {
            throw new \InvalidArgumentException('non-nullable flow_type cannot be null');
        }
        $this->container['flow_type'] = $flow_type;

        return $this;
    }

    /**
     * Gets fractional_odds_value
     *
     * @return string|null
     */
    public function getFractionalOddsValue()
    {
        return $this->container['fractional_odds_value'];
    }

    /**
     * Sets fractional_odds_value
     *
     * @param string|null $fractional_odds_value fractional_odds_value
     *
     * @return self
     */
    public function setFractionalOddsValue($fractional_odds_value)
    {
        if (is_null($fractional_odds_value)) {
            array_push($this->openAPINullablesSetToNull, 'fractional_odds_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fractional_odds_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fractional_odds_value'] = $fractional_odds_value;

        return $this;
    }

    /**
     * Gets is_combinable
     *
     * @return bool|null
     */
    public function getIsCombinable()
    {
        return $this->container['is_combinable'];
    }

    /**
     * Sets is_combinable
     *
     * @param bool|null $is_combinable Parlay only. False if any leg failed or the parlay-level uncombinable roll fired.
     *
     * @return self
     */
    public function setIsCombinable($is_combinable)
    {
        if (is_null($is_combinable)) {
            throw new \InvalidArgumentException('non-nullable is_combinable cannot be null');
        }
        $this->container['is_combinable'] = $is_combinable;

        return $this;
    }

    /**
     * Gets odds_implied_probability
     *
     * @return float|null
     */
    public function getOddsImpliedProbability()
    {
        return $this->container['odds_implied_probability'];
    }

    /**
     * Sets odds_implied_probability
     *
     * @param float|null $odds_implied_probability odds_implied_probability
     *
     * @return self
     */
    public function setOddsImpliedProbability($odds_implied_probability)
    {
        if (is_null($odds_implied_probability)) {
            array_push($this->openAPINullablesSetToNull, 'odds_implied_probability');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('odds_implied_probability', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['odds_implied_probability'] = $odds_implied_probability;

        return $this;
    }

    /**
     * Gets parlay_failure_reason
     *
     * @return string|null
     */
    public function getParlayFailureReason()
    {
        return $this->container['parlay_failure_reason'];
    }

    /**
     * Sets parlay_failure_reason
     *
     * @param string|null $parlay_failure_reason parlay_failure_reason
     *
     * @return self
     */
    public function setParlayFailureReason($parlay_failure_reason)
    {
        if (is_null($parlay_failure_reason)) {
            array_push($this->openAPINullablesSetToNull, 'parlay_failure_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parlay_failure_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getParlayFailureReasonAllowableValues();
        if (!is_null($parlay_failure_reason) && !in_array($parlay_failure_reason, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'parlay_failure_reason', must be one of '%s'",
                    $parlay_failure_reason,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['parlay_failure_reason'] = $parlay_failure_reason;

        return $this;
    }

    /**
     * Gets payout_multiplier
     *
     * @return float|null
     */
    public function getPayoutMultiplier()
    {
        return $this->container['payout_multiplier'];
    }

    /**
     * Sets payout_multiplier
     *
     * @param float|null $payout_multiplier payout_multiplier
     *
     * @return self
     */
    public function setPayoutMultiplier($payout_multiplier)
    {
        if (is_null($payout_multiplier)) {
            array_push($this->openAPINullablesSetToNull, 'payout_multiplier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payout_multiplier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payout_multiplier'] = $payout_multiplier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


