<?php
/**
 * TrendsQuoteFlowItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * TrendsQuoteFlowItem Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TrendsQuoteFlowItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'trends_QuoteFlowItem';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'country' => 'string',
        'event_betting_market_position_ids' => 'int[]',
        'flow_id' => 'int',
        'flow_type' => 'string',
        'region' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'country' => null,
        'event_betting_market_position_ids' => 'int64',
        'flow_id' => 'int64',
        'flow_type' => null,
        'region' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'country' => false,
        'event_betting_market_position_ids' => false,
        'flow_id' => false,
        'flow_type' => false,
        'region' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country' => 'country',
        'event_betting_market_position_ids' => 'event_betting_market_position_ids',
        'flow_id' => 'flow_id',
        'flow_type' => 'flow_type',
        'region' => 'region'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country' => 'setCountry',
        'event_betting_market_position_ids' => 'setEventBettingMarketPositionIds',
        'flow_id' => 'setFlowId',
        'flow_type' => 'setFlowType',
        'region' => 'setRegion'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country' => 'getCountry',
        'event_betting_market_position_ids' => 'getEventBettingMarketPositionIds',
        'flow_id' => 'getFlowId',
        'flow_type' => 'getFlowType',
        'region' => 'getRegion'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FLOW_TYPE_FACT_FLOW = 'fact_flow';
    public const FLOW_TYPE_FUN_FLOW = 'fun_flow';
    public const FLOW_TYPE_FACT_FLOW_PARLAY = 'fact_flow_parlay';
    public const FLOW_TYPE_FUN_FLOW_PARLAY = 'fun_flow_parlay';
    public const FLOW_TYPE_PLAIN_FLOW_PARLAY = 'plain_flow_parlay';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFlowTypeAllowableValues()
    {
        return [
            self::FLOW_TYPE_FACT_FLOW,
            self::FLOW_TYPE_FUN_FLOW,
            self::FLOW_TYPE_FACT_FLOW_PARLAY,
            self::FLOW_TYPE_FUN_FLOW_PARLAY,
            self::FLOW_TYPE_PLAIN_FLOW_PARLAY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('event_betting_market_position_ids', $data ?? [], null);
        $this->setIfExists('flow_id', $data ?? [], null);
        $this->setIfExists('flow_type', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        if ((mb_strlen($this->container['country']) > 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be smaller than or equal to 2.";
        }

        if ((mb_strlen($this->container['country']) < 2)) {
            $invalidProperties[] = "invalid value for 'country', the character length must be bigger than or equal to 2.";
        }

        if ($this->container['event_betting_market_position_ids'] === null) {
            $invalidProperties[] = "'event_betting_market_position_ids' can't be null";
        }
        if ((count($this->container['event_betting_market_position_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'event_betting_market_position_ids', number of items must be greater than or equal to 1.";
        }

        if ($this->container['flow_id'] === null) {
            $invalidProperties[] = "'flow_id' can't be null";
        }
        if (($this->container['flow_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'flow_id', must be bigger than or equal to 1.";
        }

        if ($this->container['flow_type'] === null) {
            $invalidProperties[] = "'flow_type' can't be null";
        }
        $allowedValues = $this->getFlowTypeAllowableValues();
        if (!is_null($this->container['flow_type']) && !in_array($this->container['flow_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'flow_type', must be one of '%s'",
                $this->container['flow_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['region']) && (mb_strlen($this->container['region']) > 3)) {
            $invalidProperties[] = "invalid value for 'region', the character length must be smaller than or equal to 3.";
        }

        if (!is_null($this->container['region']) && (mb_strlen($this->container['region']) < 2)) {
            $invalidProperties[] = "invalid value for 'region', the character length must be bigger than or equal to 2.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country ISO 3166-1 alpha-2 country code (e.g. 'US', 'IT'). Uppercased server-side.
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        if ((mb_strlen($country) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling TrendsQuoteFlowItem., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($country) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country when calling TrendsQuoteFlowItem., must be bigger than or equal to 2.');
        }

        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets event_betting_market_position_ids
     *
     * @return int[]
     */
    public function getEventBettingMarketPositionIds()
    {
        return $this->container['event_betting_market_position_ids'];
    }

    /**
     * Sets event_betting_market_position_ids
     *
     * @param int[] $event_betting_market_position_ids Leg identifiers that make up this flow. Length 1 = single, length 2+ = parlay.
     *
     * @return self
     */
    public function setEventBettingMarketPositionIds($event_betting_market_position_ids)
    {
        if (is_null($event_betting_market_position_ids)) {
            throw new \InvalidArgumentException('non-nullable event_betting_market_position_ids cannot be null');
        }


        if ((count($event_betting_market_position_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $event_betting_market_position_ids when calling TrendsQuoteFlowItem., number of items must be greater than or equal to 1.');
        }
        $this->container['event_betting_market_position_ids'] = $event_betting_market_position_ids;

        return $this;
    }

    /**
     * Gets flow_id
     *
     * @return int
     */
    public function getFlowId()
    {
        return $this->container['flow_id'];
    }

    /**
     * Sets flow_id
     *
     * @param int $flow_id flow_id
     *
     * @return self
     */
    public function setFlowId($flow_id)
    {
        if (is_null($flow_id)) {
            throw new \InvalidArgumentException('non-nullable flow_id cannot be null');
        }

        if (($flow_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $flow_id when calling TrendsQuoteFlowItem., must be bigger than or equal to 1.');
        }

        $this->container['flow_id'] = $flow_id;

        return $this;
    }

    /**
     * Gets flow_type
     *
     * @return string
     */
    public function getFlowType()
    {
        return $this->container['flow_type'];
    }

    /**
     * Sets flow_type
     *
     * @param string $flow_type flow_type
     *
     * @return self
     */
    public function setFlowType($flow_type)
    {
        if (is_null($flow_type)) {
            throw new \InvalidArgumentException('non-nullable flow_type cannot be null');
        }
        $allowedValues = $this->getFlowTypeAllowableValues();
        if (!in_array($flow_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'flow_type', must be one of '%s'",
                    $flow_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['flow_type'] = $flow_type;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string|null $region Sub-national region code (e.g. 'NJ', 'WA'). Uppercased server-side.
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        if ((mb_strlen($region) > 3)) {
            throw new \InvalidArgumentException('invalid length for $region when calling TrendsQuoteFlowItem., must be smaller than or equal to 3.');
        }
        if ((mb_strlen($region) < 2)) {
            throw new \InvalidArgumentException('invalid length for $region when calling TrendsQuoteFlowItem., must be bigger than or equal to 2.');
        }

        $this->container['region'] = $region;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


