<?php
/**
 * V1AffiliatesOffersPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * V1AffiliatesOffersPostRequest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1AffiliatesOffersPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_v1_affiliates_offers_post_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'country_code' => 'string',
        'excluded_operator_ids' => 'int[]',
        'hide_offers_links' => 'bool',
        'offer_campaign' => 'string',
        'operator_ids' => 'int[]',
        'operator_keys' => 'string[]',
        'operator_type_ids' => 'int[]',
        'subnational_region_code' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'country_code' => null,
        'excluded_operator_ids' => 'int64',
        'hide_offers_links' => null,
        'offer_campaign' => null,
        'operator_ids' => 'int64',
        'operator_keys' => null,
        'operator_type_ids' => 'int64',
        'subnational_region_code' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'country_code' => false,
        'excluded_operator_ids' => false,
        'hide_offers_links' => false,
        'offer_campaign' => false,
        'operator_ids' => false,
        'operator_keys' => false,
        'operator_type_ids' => false,
        'subnational_region_code' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country_code' => 'country_code',
        'excluded_operator_ids' => 'excluded_operator_ids',
        'hide_offers_links' => 'hide_offers_links',
        'offer_campaign' => 'offer_campaign',
        'operator_ids' => 'operator_ids',
        'operator_keys' => 'operator_keys',
        'operator_type_ids' => 'operator_type_ids',
        'subnational_region_code' => 'subnational_region_code'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country_code' => 'setCountryCode',
        'excluded_operator_ids' => 'setExcludedOperatorIds',
        'hide_offers_links' => 'setHideOffersLinks',
        'offer_campaign' => 'setOfferCampaign',
        'operator_ids' => 'setOperatorIds',
        'operator_keys' => 'setOperatorKeys',
        'operator_type_ids' => 'setOperatorTypeIds',
        'subnational_region_code' => 'setSubnationalRegionCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country_code' => 'getCountryCode',
        'excluded_operator_ids' => 'getExcludedOperatorIds',
        'hide_offers_links' => 'getHideOffersLinks',
        'offer_campaign' => 'getOfferCampaign',
        'operator_ids' => 'getOperatorIds',
        'operator_keys' => 'getOperatorKeys',
        'operator_type_ids' => 'getOperatorTypeIds',
        'subnational_region_code' => 'getSubnationalRegionCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('country_code', $data ?? [], 'US');
        $this->setIfExists('excluded_operator_ids', $data ?? [], null);
        $this->setIfExists('hide_offers_links', $data ?? [], null);
        $this->setIfExists('offer_campaign', $data ?? [], null);
        $this->setIfExists('operator_ids', $data ?? [], null);
        $this->setIfExists('operator_keys', $data ?? [], null);
        $this->setIfExists('operator_type_ids', $data ?? [], null);
        $this->setIfExists('subnational_region_code', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['country_code']) && (mb_strlen($this->container['country_code']) > 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['country_code']) && (mb_strlen($this->container['country_code']) < 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['subnational_region_code']) && (mb_strlen($this->container['subnational_region_code']) > 10)) {
            $invalidProperties[] = "invalid value for 'subnational_region_code', the character length must be smaller than or equal to 10.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country_code
     *
     * @return string|null
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string|null $country_code country_code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        if ((mb_strlen($country_code) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling V1AffiliatesOffersPostRequest., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($country_code) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling V1AffiliatesOffersPostRequest., must be bigger than or equal to 2.');
        }

        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets excluded_operator_ids
     *
     * @return int[]|null
     */
    public function getExcludedOperatorIds()
    {
        return $this->container['excluded_operator_ids'];
    }

    /**
     * Sets excluded_operator_ids
     *
     * @param int[]|null $excluded_operator_ids excluded_operator_ids
     *
     * @return self
     */
    public function setExcludedOperatorIds($excluded_operator_ids)
    {
        if (is_null($excluded_operator_ids)) {
            throw new \InvalidArgumentException('non-nullable excluded_operator_ids cannot be null');
        }
        $this->container['excluded_operator_ids'] = $excluded_operator_ids;

        return $this;
    }

    /**
     * Gets hide_offers_links
     *
     * @return bool|null
     */
    public function getHideOffersLinks()
    {
        return $this->container['hide_offers_links'];
    }

    /**
     * Sets hide_offers_links
     *
     * @param bool|null $hide_offers_links hide_offers_links
     *
     * @return self
     */
    public function setHideOffersLinks($hide_offers_links)
    {
        if (is_null($hide_offers_links)) {
            throw new \InvalidArgumentException('non-nullable hide_offers_links cannot be null');
        }
        $this->container['hide_offers_links'] = $hide_offers_links;

        return $this;
    }

    /**
     * Gets offer_campaign
     *
     * @return string|null
     */
    public function getOfferCampaign()
    {
        return $this->container['offer_campaign'];
    }

    /**
     * Sets offer_campaign
     *
     * @param string|null $offer_campaign offer_campaign
     *
     * @return self
     */
    public function setOfferCampaign($offer_campaign)
    {
        if (is_null($offer_campaign)) {
            throw new \InvalidArgumentException('non-nullable offer_campaign cannot be null');
        }
        $this->container['offer_campaign'] = $offer_campaign;

        return $this;
    }

    /**
     * Gets operator_ids
     *
     * @return int[]|null
     */
    public function getOperatorIds()
    {
        return $this->container['operator_ids'];
    }

    /**
     * Sets operator_ids
     *
     * @param int[]|null $operator_ids operator_ids
     *
     * @return self
     */
    public function setOperatorIds($operator_ids)
    {
        if (is_null($operator_ids)) {
            throw new \InvalidArgumentException('non-nullable operator_ids cannot be null');
        }
        $this->container['operator_ids'] = $operator_ids;

        return $this;
    }

    /**
     * Gets operator_keys
     *
     * @return string[]|null
     */
    public function getOperatorKeys()
    {
        return $this->container['operator_keys'];
    }

    /**
     * Sets operator_keys
     *
     * @param string[]|null $operator_keys operator_keys
     *
     * @return self
     */
    public function setOperatorKeys($operator_keys)
    {
        if (is_null($operator_keys)) {
            throw new \InvalidArgumentException('non-nullable operator_keys cannot be null');
        }
        $this->container['operator_keys'] = $operator_keys;

        return $this;
    }

    /**
     * Gets operator_type_ids
     *
     * @return int[]|null
     */
    public function getOperatorTypeIds()
    {
        return $this->container['operator_type_ids'];
    }

    /**
     * Sets operator_type_ids
     *
     * @param int[]|null $operator_type_ids operator_type_ids
     *
     * @return self
     */
    public function setOperatorTypeIds($operator_type_ids)
    {
        if (is_null($operator_type_ids)) {
            throw new \InvalidArgumentException('non-nullable operator_type_ids cannot be null');
        }
        $this->container['operator_type_ids'] = $operator_type_ids;

        return $this;
    }

    /**
     * Gets subnational_region_code
     *
     * @return string|null
     */
    public function getSubnationalRegionCode()
    {
        return $this->container['subnational_region_code'];
    }

    /**
     * Sets subnational_region_code
     *
     * @param string|null $subnational_region_code subnational_region_code
     *
     * @return self
     */
    public function setSubnationalRegionCode($subnational_region_code)
    {
        if (is_null($subnational_region_code)) {
            throw new \InvalidArgumentException('non-nullable subnational_region_code cannot be null');
        }
        if ((mb_strlen($subnational_region_code) > 10)) {
            throw new \InvalidArgumentException('invalid length for $subnational_region_code when calling V1AffiliatesOffersPostRequest., must be smaller than or equal to 10.');
        }

        $this->container['subnational_region_code'] = $subnational_region_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


