<?php
/**
 * V1AffiliatesEventsPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * V1AffiliatesEventsPostRequest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1AffiliatesEventsPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_v1_affiliates_events_post_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'country_code' => 'string',
        'device_type' => 'string',
        'event_type' => 'string',
        'offer_campaign' => 'string',
        'offer_id' => 'string',
        'offer_label' => 'string',
        'operator_id' => 'int',
        'session_token' => 'string',
        'subnational_region_code' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'country_code' => null,
        'device_type' => null,
        'event_type' => null,
        'offer_campaign' => null,
        'offer_id' => 'uuid',
        'offer_label' => null,
        'operator_id' => 'int64',
        'session_token' => null,
        'subnational_region_code' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'country_code' => false,
        'device_type' => false,
        'event_type' => false,
        'offer_campaign' => false,
        'offer_id' => false,
        'offer_label' => false,
        'operator_id' => false,
        'session_token' => false,
        'subnational_region_code' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country_code' => 'country_code',
        'device_type' => 'device_type',
        'event_type' => 'event_type',
        'offer_campaign' => 'offer_campaign',
        'offer_id' => 'offer_id',
        'offer_label' => 'offer_label',
        'operator_id' => 'operator_id',
        'session_token' => 'session_token',
        'subnational_region_code' => 'subnational_region_code'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country_code' => 'setCountryCode',
        'device_type' => 'setDeviceType',
        'event_type' => 'setEventType',
        'offer_campaign' => 'setOfferCampaign',
        'offer_id' => 'setOfferId',
        'offer_label' => 'setOfferLabel',
        'operator_id' => 'setOperatorId',
        'session_token' => 'setSessionToken',
        'subnational_region_code' => 'setSubnationalRegionCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country_code' => 'getCountryCode',
        'device_type' => 'getDeviceType',
        'event_type' => 'getEventType',
        'offer_campaign' => 'getOfferCampaign',
        'offer_id' => 'getOfferId',
        'offer_label' => 'getOfferLabel',
        'operator_id' => 'getOperatorId',
        'session_token' => 'getSessionToken',
        'subnational_region_code' => 'getSubnationalRegionCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const DEVICE_TYPE_IOS = 'ios';
    public const DEVICE_TYPE_ANDROID = 'android';
    public const DEVICE_TYPE_DESKTOP = 'desktop';
    public const EVENT_TYPE_IMPRESSION = 'impression';
    public const EVENT_TYPE_CLICK = 'click';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeviceTypeAllowableValues()
    {
        return [
            self::DEVICE_TYPE_IOS,
            self::DEVICE_TYPE_ANDROID,
            self::DEVICE_TYPE_DESKTOP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEventTypeAllowableValues()
    {
        return [
            self::EVENT_TYPE_IMPRESSION,
            self::EVENT_TYPE_CLICK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('country_code', $data ?? [], null);
        $this->setIfExists('device_type', $data ?? [], null);
        $this->setIfExists('event_type', $data ?? [], null);
        $this->setIfExists('offer_campaign', $data ?? [], null);
        $this->setIfExists('offer_id', $data ?? [], null);
        $this->setIfExists('offer_label', $data ?? [], null);
        $this->setIfExists('operator_id', $data ?? [], null);
        $this->setIfExists('session_token', $data ?? [], null);
        $this->setIfExists('subnational_region_code', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['country_code'] === null) {
            $invalidProperties[] = "'country_code' can't be null";
        }
        if ((mb_strlen($this->container['country_code']) > 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be smaller than or equal to 2.";
        }

        if ((mb_strlen($this->container['country_code']) < 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be bigger than or equal to 2.";
        }

        $allowedValues = $this->getDeviceTypeAllowableValues();
        if (!is_null($this->container['device_type']) && !in_array($this->container['device_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'device_type', must be one of '%s'",
                $this->container['device_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['event_type'] === null) {
            $invalidProperties[] = "'event_type' can't be null";
        }
        $allowedValues = $this->getEventTypeAllowableValues();
        if (!is_null($this->container['event_type']) && !in_array($this->container['event_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'event_type', must be one of '%s'",
                $this->container['event_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['offer_campaign']) && (mb_strlen($this->container['offer_campaign']) > 255)) {
            $invalidProperties[] = "invalid value for 'offer_campaign', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['offer_id'] === null) {
            $invalidProperties[] = "'offer_id' can't be null";
        }
        if (!is_null($this->container['offer_label']) && (mb_strlen($this->container['offer_label']) > 255)) {
            $invalidProperties[] = "invalid value for 'offer_label', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['operator_id'] === null) {
            $invalidProperties[] = "'operator_id' can't be null";
        }
        if (($this->container['operator_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'operator_id', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['session_token']) && (mb_strlen($this->container['session_token']) > 64)) {
            $invalidProperties[] = "invalid value for 'session_token', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['subnational_region_code']) && (mb_strlen($this->container['subnational_region_code']) > 10)) {
            $invalidProperties[] = "invalid value for 'subnational_region_code', the character length must be smaller than or equal to 10.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country_code
     *
     * @return string
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string $country_code country_code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        if ((mb_strlen($country_code) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling V1AffiliatesEventsPostRequest., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($country_code) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling V1AffiliatesEventsPostRequest., must be bigger than or equal to 2.');
        }

        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets device_type
     *
     * @return string|null
     */
    public function getDeviceType()
    {
        return $this->container['device_type'];
    }

    /**
     * Sets device_type
     *
     * @param string|null $device_type device_type
     *
     * @return self
     */
    public function setDeviceType($device_type)
    {
        if (is_null($device_type)) {
            throw new \InvalidArgumentException('non-nullable device_type cannot be null');
        }
        $allowedValues = $this->getDeviceTypeAllowableValues();
        if (!in_array($device_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'device_type', must be one of '%s'",
                    $device_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['device_type'] = $device_type;

        return $this;
    }

    /**
     * Gets event_type
     *
     * @return string
     */
    public function getEventType()
    {
        return $this->container['event_type'];
    }

    /**
     * Sets event_type
     *
     * @param string $event_type event_type
     *
     * @return self
     */
    public function setEventType($event_type)
    {
        if (is_null($event_type)) {
            throw new \InvalidArgumentException('non-nullable event_type cannot be null');
        }
        $allowedValues = $this->getEventTypeAllowableValues();
        if (!in_array($event_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'event_type', must be one of '%s'",
                    $event_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['event_type'] = $event_type;

        return $this;
    }

    /**
     * Gets offer_campaign
     *
     * @return string|null
     */
    public function getOfferCampaign()
    {
        return $this->container['offer_campaign'];
    }

    /**
     * Sets offer_campaign
     *
     * @param string|null $offer_campaign offer_campaign
     *
     * @return self
     */
    public function setOfferCampaign($offer_campaign)
    {
        if (is_null($offer_campaign)) {
            throw new \InvalidArgumentException('non-nullable offer_campaign cannot be null');
        }
        if ((mb_strlen($offer_campaign) > 255)) {
            throw new \InvalidArgumentException('invalid length for $offer_campaign when calling V1AffiliatesEventsPostRequest., must be smaller than or equal to 255.');
        }

        $this->container['offer_campaign'] = $offer_campaign;

        return $this;
    }

    /**
     * Gets offer_id
     *
     * @return string
     */
    public function getOfferId()
    {
        return $this->container['offer_id'];
    }

    /**
     * Sets offer_id
     *
     * @param string $offer_id offer_id
     *
     * @return self
     */
    public function setOfferId($offer_id)
    {
        if (is_null($offer_id)) {
            throw new \InvalidArgumentException('non-nullable offer_id cannot be null');
        }
        $this->container['offer_id'] = $offer_id;

        return $this;
    }

    /**
     * Gets offer_label
     *
     * @return string|null
     */
    public function getOfferLabel()
    {
        return $this->container['offer_label'];
    }

    /**
     * Sets offer_label
     *
     * @param string|null $offer_label offer_label
     *
     * @return self
     */
    public function setOfferLabel($offer_label)
    {
        if (is_null($offer_label)) {
            throw new \InvalidArgumentException('non-nullable offer_label cannot be null');
        }
        if ((mb_strlen($offer_label) > 255)) {
            throw new \InvalidArgumentException('invalid length for $offer_label when calling V1AffiliatesEventsPostRequest., must be smaller than or equal to 255.');
        }

        $this->container['offer_label'] = $offer_label;

        return $this;
    }

    /**
     * Gets operator_id
     *
     * @return int
     */
    public function getOperatorId()
    {
        return $this->container['operator_id'];
    }

    /**
     * Sets operator_id
     *
     * @param int $operator_id operator_id
     *
     * @return self
     */
    public function setOperatorId($operator_id)
    {
        if (is_null($operator_id)) {
            throw new \InvalidArgumentException('non-nullable operator_id cannot be null');
        }

        if (($operator_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $operator_id when calling V1AffiliatesEventsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['operator_id'] = $operator_id;

        return $this;
    }

    /**
     * Gets session_token
     *
     * @return string|null
     */
    public function getSessionToken()
    {
        return $this->container['session_token'];
    }

    /**
     * Sets session_token
     *
     * @param string|null $session_token session_token
     *
     * @return self
     */
    public function setSessionToken($session_token)
    {
        if (is_null($session_token)) {
            throw new \InvalidArgumentException('non-nullable session_token cannot be null');
        }
        if ((mb_strlen($session_token) > 64)) {
            throw new \InvalidArgumentException('invalid length for $session_token when calling V1AffiliatesEventsPostRequest., must be smaller than or equal to 64.');
        }

        $this->container['session_token'] = $session_token;

        return $this;
    }

    /**
     * Gets subnational_region_code
     *
     * @return string|null
     */
    public function getSubnationalRegionCode()
    {
        return $this->container['subnational_region_code'];
    }

    /**
     * Sets subnational_region_code
     *
     * @param string|null $subnational_region_code subnational_region_code
     *
     * @return self
     */
    public function setSubnationalRegionCode($subnational_region_code)
    {
        if (is_null($subnational_region_code)) {
            throw new \InvalidArgumentException('non-nullable subnational_region_code cannot be null');
        }
        if ((mb_strlen($subnational_region_code) > 10)) {
            throw new \InvalidArgumentException('invalid length for $subnational_region_code when calling V1AffiliatesEventsPostRequest., must be smaller than or equal to 10.');
        }

        $this->container['subnational_region_code'] = $subnational_region_code;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


