<?php
/**
 * V1AffiliatesLinksPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * V1AffiliatesLinksPostRequest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1AffiliatesLinksPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_v1_affiliates_links_post_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'android_deep_link_url' => 'string',
        'country_code' => 'string',
        'ios_deep_link_url' => 'string',
        'is_active' => 'bool',
        'offer_call_to_action' => 'string',
        'offer_campaign' => 'string',
        'offer_category_id' => 'int',
        'offer_display_bullets' => 'string[]',
        'offer_display_small_print' => 'string',
        'offer_ev_usd' => 'float',
        'offer_label' => 'string',
        'offer_priority' => 'int',
        'offer_tagline' => 'string',
        'operator_id' => 'int',
        'operator_name' => 'string',
        'source_network_affiliate_partner_id' => 'int',
        'subnational_region_code' => 'string',
        'web_deep_link_url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'android_deep_link_url' => 'uri',
        'country_code' => null,
        'ios_deep_link_url' => 'uri',
        'is_active' => null,
        'offer_call_to_action' => null,
        'offer_campaign' => null,
        'offer_category_id' => 'int64',
        'offer_display_bullets' => null,
        'offer_display_small_print' => null,
        'offer_ev_usd' => null,
        'offer_label' => null,
        'offer_priority' => null,
        'offer_tagline' => null,
        'operator_id' => 'int64',
        'operator_name' => null,
        'source_network_affiliate_partner_id' => 'int64',
        'subnational_region_code' => null,
        'web_deep_link_url' => 'uri'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'android_deep_link_url' => false,
        'country_code' => false,
        'ios_deep_link_url' => false,
        'is_active' => false,
        'offer_call_to_action' => false,
        'offer_campaign' => false,
        'offer_category_id' => false,
        'offer_display_bullets' => false,
        'offer_display_small_print' => false,
        'offer_ev_usd' => false,
        'offer_label' => false,
        'offer_priority' => false,
        'offer_tagline' => false,
        'operator_id' => false,
        'operator_name' => false,
        'source_network_affiliate_partner_id' => false,
        'subnational_region_code' => false,
        'web_deep_link_url' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'android_deep_link_url' => 'android_deep_link_url',
        'country_code' => 'country_code',
        'ios_deep_link_url' => 'ios_deep_link_url',
        'is_active' => 'is_active',
        'offer_call_to_action' => 'offer_call_to_action',
        'offer_campaign' => 'offer_campaign',
        'offer_category_id' => 'offer_category_id',
        'offer_display_bullets' => 'offer_display_bullets',
        'offer_display_small_print' => 'offer_display_small_print',
        'offer_ev_usd' => 'offer_ev_usd',
        'offer_label' => 'offer_label',
        'offer_priority' => 'offer_priority',
        'offer_tagline' => 'offer_tagline',
        'operator_id' => 'operator_id',
        'operator_name' => 'operator_name',
        'source_network_affiliate_partner_id' => 'source_network_affiliate_partner_id',
        'subnational_region_code' => 'subnational_region_code',
        'web_deep_link_url' => 'web_deep_link_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'android_deep_link_url' => 'setAndroidDeepLinkUrl',
        'country_code' => 'setCountryCode',
        'ios_deep_link_url' => 'setIosDeepLinkUrl',
        'is_active' => 'setIsActive',
        'offer_call_to_action' => 'setOfferCallToAction',
        'offer_campaign' => 'setOfferCampaign',
        'offer_category_id' => 'setOfferCategoryId',
        'offer_display_bullets' => 'setOfferDisplayBullets',
        'offer_display_small_print' => 'setOfferDisplaySmallPrint',
        'offer_ev_usd' => 'setOfferEvUsd',
        'offer_label' => 'setOfferLabel',
        'offer_priority' => 'setOfferPriority',
        'offer_tagline' => 'setOfferTagline',
        'operator_id' => 'setOperatorId',
        'operator_name' => 'setOperatorName',
        'source_network_affiliate_partner_id' => 'setSourceNetworkAffiliatePartnerId',
        'subnational_region_code' => 'setSubnationalRegionCode',
        'web_deep_link_url' => 'setWebDeepLinkUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'android_deep_link_url' => 'getAndroidDeepLinkUrl',
        'country_code' => 'getCountryCode',
        'ios_deep_link_url' => 'getIosDeepLinkUrl',
        'is_active' => 'getIsActive',
        'offer_call_to_action' => 'getOfferCallToAction',
        'offer_campaign' => 'getOfferCampaign',
        'offer_category_id' => 'getOfferCategoryId',
        'offer_display_bullets' => 'getOfferDisplayBullets',
        'offer_display_small_print' => 'getOfferDisplaySmallPrint',
        'offer_ev_usd' => 'getOfferEvUsd',
        'offer_label' => 'getOfferLabel',
        'offer_priority' => 'getOfferPriority',
        'offer_tagline' => 'getOfferTagline',
        'operator_id' => 'getOperatorId',
        'operator_name' => 'getOperatorName',
        'source_network_affiliate_partner_id' => 'getSourceNetworkAffiliatePartnerId',
        'subnational_region_code' => 'getSubnationalRegionCode',
        'web_deep_link_url' => 'getWebDeepLinkUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('android_deep_link_url', $data ?? [], null);
        $this->setIfExists('country_code', $data ?? [], 'US');
        $this->setIfExists('ios_deep_link_url', $data ?? [], null);
        $this->setIfExists('is_active', $data ?? [], true);
        $this->setIfExists('offer_call_to_action', $data ?? [], null);
        $this->setIfExists('offer_campaign', $data ?? [], null);
        $this->setIfExists('offer_category_id', $data ?? [], null);
        $this->setIfExists('offer_display_bullets', $data ?? [], null);
        $this->setIfExists('offer_display_small_print', $data ?? [], null);
        $this->setIfExists('offer_ev_usd', $data ?? [], null);
        $this->setIfExists('offer_label', $data ?? [], null);
        $this->setIfExists('offer_priority', $data ?? [], null);
        $this->setIfExists('offer_tagline', $data ?? [], null);
        $this->setIfExists('operator_id', $data ?? [], null);
        $this->setIfExists('operator_name', $data ?? [], null);
        $this->setIfExists('source_network_affiliate_partner_id', $data ?? [], null);
        $this->setIfExists('subnational_region_code', $data ?? [], null);
        $this->setIfExists('web_deep_link_url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['country_code']) && (mb_strlen($this->container['country_code']) > 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be smaller than or equal to 2.";
        }

        if (!is_null($this->container['country_code']) && (mb_strlen($this->container['country_code']) < 2)) {
            $invalidProperties[] = "invalid value for 'country_code', the character length must be bigger than or equal to 2.";
        }

        if (!is_null($this->container['offer_campaign']) && (mb_strlen($this->container['offer_campaign']) > 255)) {
            $invalidProperties[] = "invalid value for 'offer_campaign', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['offer_category_id'] === null) {
            $invalidProperties[] = "'offer_category_id' can't be null";
        }
        if (!is_null($this->container['offer_display_small_print']) && (mb_strlen($this->container['offer_display_small_print']) > 255)) {
            $invalidProperties[] = "invalid value for 'offer_display_small_print', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['offer_label']) && (mb_strlen($this->container['offer_label']) > 255)) {
            $invalidProperties[] = "invalid value for 'offer_label', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['offer_tagline']) && (mb_strlen($this->container['offer_tagline']) > 255)) {
            $invalidProperties[] = "invalid value for 'offer_tagline', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['subnational_region_code']) && (mb_strlen($this->container['subnational_region_code']) > 10)) {
            $invalidProperties[] = "invalid value for 'subnational_region_code', the character length must be smaller than or equal to 10.";
        }

        if ($this->container['web_deep_link_url'] === null) {
            $invalidProperties[] = "'web_deep_link_url' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets android_deep_link_url
     *
     * @return string|null
     */
    public function getAndroidDeepLinkUrl()
    {
        return $this->container['android_deep_link_url'];
    }

    /**
     * Sets android_deep_link_url
     *
     * @param string|null $android_deep_link_url android_deep_link_url
     *
     * @return self
     */
    public function setAndroidDeepLinkUrl($android_deep_link_url)
    {
        if (is_null($android_deep_link_url)) {
            throw new \InvalidArgumentException('non-nullable android_deep_link_url cannot be null');
        }
        $this->container['android_deep_link_url'] = $android_deep_link_url;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return string|null
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string|null $country_code country_code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        if ((mb_strlen($country_code) > 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling V1AffiliatesLinksPostRequest., must be smaller than or equal to 2.');
        }
        if ((mb_strlen($country_code) < 2)) {
            throw new \InvalidArgumentException('invalid length for $country_code when calling V1AffiliatesLinksPostRequest., must be bigger than or equal to 2.');
        }

        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets ios_deep_link_url
     *
     * @return string|null
     */
    public function getIosDeepLinkUrl()
    {
        return $this->container['ios_deep_link_url'];
    }

    /**
     * Sets ios_deep_link_url
     *
     * @param string|null $ios_deep_link_url ios_deep_link_url
     *
     * @return self
     */
    public function setIosDeepLinkUrl($ios_deep_link_url)
    {
        if (is_null($ios_deep_link_url)) {
            throw new \InvalidArgumentException('non-nullable ios_deep_link_url cannot be null');
        }
        $this->container['ios_deep_link_url'] = $ios_deep_link_url;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool|null
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool|null $is_active is_active
     *
     * @return self
     */
    public function setIsActive($is_active)
    {
        if (is_null($is_active)) {
            throw new \InvalidArgumentException('non-nullable is_active cannot be null');
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets offer_call_to_action
     *
     * @return string|null
     */
    public function getOfferCallToAction()
    {
        return $this->container['offer_call_to_action'];
    }

    /**
     * Sets offer_call_to_action
     *
     * @param string|null $offer_call_to_action offer_call_to_action
     *
     * @return self
     */
    public function setOfferCallToAction($offer_call_to_action)
    {
        if (is_null($offer_call_to_action)) {
            throw new \InvalidArgumentException('non-nullable offer_call_to_action cannot be null');
        }
        $this->container['offer_call_to_action'] = $offer_call_to_action;

        return $this;
    }

    /**
     * Gets offer_campaign
     *
     * @return string|null
     */
    public function getOfferCampaign()
    {
        return $this->container['offer_campaign'];
    }

    /**
     * Sets offer_campaign
     *
     * @param string|null $offer_campaign offer_campaign
     *
     * @return self
     */
    public function setOfferCampaign($offer_campaign)
    {
        if (is_null($offer_campaign)) {
            throw new \InvalidArgumentException('non-nullable offer_campaign cannot be null');
        }
        if ((mb_strlen($offer_campaign) > 255)) {
            throw new \InvalidArgumentException('invalid length for $offer_campaign when calling V1AffiliatesLinksPostRequest., must be smaller than or equal to 255.');
        }

        $this->container['offer_campaign'] = $offer_campaign;

        return $this;
    }

    /**
     * Gets offer_category_id
     *
     * @return int
     */
    public function getOfferCategoryId()
    {
        return $this->container['offer_category_id'];
    }

    /**
     * Sets offer_category_id
     *
     * @param int $offer_category_id offer_category_id
     *
     * @return self
     */
    public function setOfferCategoryId($offer_category_id)
    {
        if (is_null($offer_category_id)) {
            throw new \InvalidArgumentException('non-nullable offer_category_id cannot be null');
        }
        $this->container['offer_category_id'] = $offer_category_id;

        return $this;
    }

    /**
     * Gets offer_display_bullets
     *
     * @return string[]|null
     */
    public function getOfferDisplayBullets()
    {
        return $this->container['offer_display_bullets'];
    }

    /**
     * Sets offer_display_bullets
     *
     * @param string[]|null $offer_display_bullets offer_display_bullets
     *
     * @return self
     */
    public function setOfferDisplayBullets($offer_display_bullets)
    {
        if (is_null($offer_display_bullets)) {
            throw new \InvalidArgumentException('non-nullable offer_display_bullets cannot be null');
        }
        $this->container['offer_display_bullets'] = $offer_display_bullets;

        return $this;
    }

    /**
     * Gets offer_display_small_print
     *
     * @return string|null
     */
    public function getOfferDisplaySmallPrint()
    {
        return $this->container['offer_display_small_print'];
    }

    /**
     * Sets offer_display_small_print
     *
     * @param string|null $offer_display_small_print offer_display_small_print
     *
     * @return self
     */
    public function setOfferDisplaySmallPrint($offer_display_small_print)
    {
        if (is_null($offer_display_small_print)) {
            throw new \InvalidArgumentException('non-nullable offer_display_small_print cannot be null');
        }
        if ((mb_strlen($offer_display_small_print) > 255)) {
            throw new \InvalidArgumentException('invalid length for $offer_display_small_print when calling V1AffiliatesLinksPostRequest., must be smaller than or equal to 255.');
        }

        $this->container['offer_display_small_print'] = $offer_display_small_print;

        return $this;
    }

    /**
     * Gets offer_ev_usd
     *
     * @return float|null
     */
    public function getOfferEvUsd()
    {
        return $this->container['offer_ev_usd'];
    }

    /**
     * Sets offer_ev_usd
     *
     * @param float|null $offer_ev_usd offer_ev_usd
     *
     * @return self
     */
    public function setOfferEvUsd($offer_ev_usd)
    {
        if (is_null($offer_ev_usd)) {
            throw new \InvalidArgumentException('non-nullable offer_ev_usd cannot be null');
        }
        $this->container['offer_ev_usd'] = $offer_ev_usd;

        return $this;
    }

    /**
     * Gets offer_label
     *
     * @return string|null
     */
    public function getOfferLabel()
    {
        return $this->container['offer_label'];
    }

    /**
     * Sets offer_label
     *
     * @param string|null $offer_label offer_label
     *
     * @return self
     */
    public function setOfferLabel($offer_label)
    {
        if (is_null($offer_label)) {
            throw new \InvalidArgumentException('non-nullable offer_label cannot be null');
        }
        if ((mb_strlen($offer_label) > 255)) {
            throw new \InvalidArgumentException('invalid length for $offer_label when calling V1AffiliatesLinksPostRequest., must be smaller than or equal to 255.');
        }

        $this->container['offer_label'] = $offer_label;

        return $this;
    }

    /**
     * Gets offer_priority
     *
     * @return int|null
     */
    public function getOfferPriority()
    {
        return $this->container['offer_priority'];
    }

    /**
     * Sets offer_priority
     *
     * @param int|null $offer_priority offer_priority
     *
     * @return self
     */
    public function setOfferPriority($offer_priority)
    {
        if (is_null($offer_priority)) {
            throw new \InvalidArgumentException('non-nullable offer_priority cannot be null');
        }
        $this->container['offer_priority'] = $offer_priority;

        return $this;
    }

    /**
     * Gets offer_tagline
     *
     * @return string|null
     */
    public function getOfferTagline()
    {
        return $this->container['offer_tagline'];
    }

    /**
     * Sets offer_tagline
     *
     * @param string|null $offer_tagline offer_tagline
     *
     * @return self
     */
    public function setOfferTagline($offer_tagline)
    {
        if (is_null($offer_tagline)) {
            throw new \InvalidArgumentException('non-nullable offer_tagline cannot be null');
        }
        if ((mb_strlen($offer_tagline) > 255)) {
            throw new \InvalidArgumentException('invalid length for $offer_tagline when calling V1AffiliatesLinksPostRequest., must be smaller than or equal to 255.');
        }

        $this->container['offer_tagline'] = $offer_tagline;

        return $this;
    }

    /**
     * Gets operator_id
     *
     * @return int|null
     */
    public function getOperatorId()
    {
        return $this->container['operator_id'];
    }

    /**
     * Sets operator_id
     *
     * @param int|null $operator_id One of operator_id or operator_name is required.
     *
     * @return self
     */
    public function setOperatorId($operator_id)
    {
        if (is_null($operator_id)) {
            throw new \InvalidArgumentException('non-nullable operator_id cannot be null');
        }
        $this->container['operator_id'] = $operator_id;

        return $this;
    }

    /**
     * Gets operator_name
     *
     * @return string|null
     */
    public function getOperatorName()
    {
        return $this->container['operator_name'];
    }

    /**
     * Sets operator_name
     *
     * @param string|null $operator_name operator_name
     *
     * @return self
     */
    public function setOperatorName($operator_name)
    {
        if (is_null($operator_name)) {
            throw new \InvalidArgumentException('non-nullable operator_name cannot be null');
        }
        $this->container['operator_name'] = $operator_name;

        return $this;
    }

    /**
     * Gets source_network_affiliate_partner_id
     *
     * @return int|null
     */
    public function getSourceNetworkAffiliatePartnerId()
    {
        return $this->container['source_network_affiliate_partner_id'];
    }

    /**
     * Sets source_network_affiliate_partner_id
     *
     * @param int|null $source_network_affiliate_partner_id source_network_affiliate_partner_id
     *
     * @return self
     */
    public function setSourceNetworkAffiliatePartnerId($source_network_affiliate_partner_id)
    {
        if (is_null($source_network_affiliate_partner_id)) {
            throw new \InvalidArgumentException('non-nullable source_network_affiliate_partner_id cannot be null');
        }
        $this->container['source_network_affiliate_partner_id'] = $source_network_affiliate_partner_id;

        return $this;
    }

    /**
     * Gets subnational_region_code
     *
     * @return string|null
     */
    public function getSubnationalRegionCode()
    {
        return $this->container['subnational_region_code'];
    }

    /**
     * Sets subnational_region_code
     *
     * @param string|null $subnational_region_code Omit for country-grain inventory.
     *
     * @return self
     */
    public function setSubnationalRegionCode($subnational_region_code)
    {
        if (is_null($subnational_region_code)) {
            throw new \InvalidArgumentException('non-nullable subnational_region_code cannot be null');
        }
        if ((mb_strlen($subnational_region_code) > 10)) {
            throw new \InvalidArgumentException('invalid length for $subnational_region_code when calling V1AffiliatesLinksPostRequest., must be smaller than or equal to 10.');
        }

        $this->container['subnational_region_code'] = $subnational_region_code;

        return $this;
    }

    /**
     * Gets web_deep_link_url
     *
     * @return string
     */
    public function getWebDeepLinkUrl()
    {
        return $this->container['web_deep_link_url'];
    }

    /**
     * Sets web_deep_link_url
     *
     * @param string $web_deep_link_url web_deep_link_url
     *
     * @return self
     */
    public function setWebDeepLinkUrl($web_deep_link_url)
    {
        if (is_null($web_deep_link_url)) {
            throw new \InvalidArgumentException('non-nullable web_deep_link_url cannot be null');
        }
        $this->container['web_deep_link_url'] = $web_deep_link_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


