<?php
/**
 * V1TrendsFlowsPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * V1TrendsFlowsPostRequest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1TrendsFlowsPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_v1_trends_flows_post_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'bet_type' => 'string',
        'betting_market_category_id' => 'int',
        'betting_market_category_ids' => 'int[]',
        'betting_market_entity_type' => 'string',
        'betting_market_ids' => 'int[]',
        'betting_market_position_id' => 'int',
        'betting_market_position_ids' => 'int[]',
        'event_id' => 'int',
        'event_ids' => 'int[]',
        'event_start_date_from' => '\DateTime',
        'event_start_date_to' => '\DateTime',
        'fact_flow_type' => 'string',
        'flow_type' => 'string',
        'focus_entity_type_id' => 'int',
        'full_hit_rate' => 'bool',
        'include_alt_lines' => 'bool',
        'include_deeplinks' => 'bool',
        'include_only_basic_trends' => 'bool',
        'include_star_sign_content' => 'bool',
        'league_id' => 'int',
        'league_ids' => 'int[]',
        'league_key' => 'string',
        'likelihood_type' => 'string',
        'max_hit_rate_threshold' => 'int',
        'max_implied_probability_threshold' => 'float',
        'min_hit_rate_threshold' => 'int',
        'min_implied_probability_threshold' => 'float',
        'odds_format' => 'string',
        'operator_ids' => 'int[]',
        'operator_keys' => 'string[]',
        'page' => 'int',
        'page_size' => 'int',
        'player_id' => 'int',
        'player_ids' => 'int[]',
        'player_key' => 'string',
        'product_mode' => 'string',
        'split_type' => 'string',
        'sport_id' => 'int',
        'sport_ids' => 'int[]',
        'sport_key' => 'string',
        'starting_soon' => 'bool',
        'team_id' => 'int',
        'team_ids' => 'int[]',
        'team_key' => 'string',
        'team_split' => 'string',
        'use_cartoon_images' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'bet_type' => null,
        'betting_market_category_id' => 'int64',
        'betting_market_category_ids' => 'int64',
        'betting_market_entity_type' => null,
        'betting_market_ids' => 'int64',
        'betting_market_position_id' => 'int64',
        'betting_market_position_ids' => 'int64',
        'event_id' => 'int64',
        'event_ids' => 'int64',
        'event_start_date_from' => 'date-time',
        'event_start_date_to' => 'date-time',
        'fact_flow_type' => null,
        'flow_type' => null,
        'focus_entity_type_id' => 'int64',
        'full_hit_rate' => null,
        'include_alt_lines' => null,
        'include_deeplinks' => null,
        'include_only_basic_trends' => null,
        'include_star_sign_content' => null,
        'league_id' => 'int64',
        'league_ids' => 'int64',
        'league_key' => null,
        'likelihood_type' => null,
        'max_hit_rate_threshold' => null,
        'max_implied_probability_threshold' => 'double',
        'min_hit_rate_threshold' => null,
        'min_implied_probability_threshold' => 'double',
        'odds_format' => null,
        'operator_ids' => 'int64',
        'operator_keys' => null,
        'page' => 'int64',
        'page_size' => 'int64',
        'player_id' => 'int64',
        'player_ids' => 'int64',
        'player_key' => null,
        'product_mode' => null,
        'split_type' => null,
        'sport_id' => 'int64',
        'sport_ids' => 'int64',
        'sport_key' => null,
        'starting_soon' => null,
        'team_id' => 'int64',
        'team_ids' => 'int64',
        'team_key' => null,
        'team_split' => null,
        'use_cartoon_images' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'bet_type' => false,
        'betting_market_category_id' => false,
        'betting_market_category_ids' => false,
        'betting_market_entity_type' => false,
        'betting_market_ids' => false,
        'betting_market_position_id' => false,
        'betting_market_position_ids' => false,
        'event_id' => false,
        'event_ids' => false,
        'event_start_date_from' => false,
        'event_start_date_to' => false,
        'fact_flow_type' => false,
        'flow_type' => false,
        'focus_entity_type_id' => false,
        'full_hit_rate' => false,
        'include_alt_lines' => false,
        'include_deeplinks' => false,
        'include_only_basic_trends' => false,
        'include_star_sign_content' => false,
        'league_id' => false,
        'league_ids' => false,
        'league_key' => false,
        'likelihood_type' => false,
        'max_hit_rate_threshold' => false,
        'max_implied_probability_threshold' => false,
        'min_hit_rate_threshold' => false,
        'min_implied_probability_threshold' => false,
        'odds_format' => false,
        'operator_ids' => false,
        'operator_keys' => false,
        'page' => false,
        'page_size' => false,
        'player_id' => false,
        'player_ids' => false,
        'player_key' => false,
        'product_mode' => false,
        'split_type' => false,
        'sport_id' => false,
        'sport_ids' => false,
        'sport_key' => false,
        'starting_soon' => false,
        'team_id' => false,
        'team_ids' => false,
        'team_key' => false,
        'team_split' => false,
        'use_cartoon_images' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bet_type' => 'bet_type',
        'betting_market_category_id' => 'betting_market_category_id',
        'betting_market_category_ids' => 'betting_market_category_ids',
        'betting_market_entity_type' => 'betting_market_entity_type',
        'betting_market_ids' => 'betting_market_ids',
        'betting_market_position_id' => 'betting_market_position_id',
        'betting_market_position_ids' => 'betting_market_position_ids',
        'event_id' => 'event_id',
        'event_ids' => 'event_ids',
        'event_start_date_from' => 'event_start_date_from',
        'event_start_date_to' => 'event_start_date_to',
        'fact_flow_type' => 'fact_flow_type',
        'flow_type' => 'flow_type',
        'focus_entity_type_id' => 'focus_entity_type_id',
        'full_hit_rate' => 'full_hit_rate',
        'include_alt_lines' => 'include_alt_lines',
        'include_deeplinks' => 'include_deeplinks',
        'include_only_basic_trends' => 'include_only_basic_trends',
        'include_star_sign_content' => 'include_star_sign_content',
        'league_id' => 'league_id',
        'league_ids' => 'league_ids',
        'league_key' => 'league_key',
        'likelihood_type' => 'likelihood_type',
        'max_hit_rate_threshold' => 'max_hit_rate_threshold',
        'max_implied_probability_threshold' => 'max_implied_probability_threshold',
        'min_hit_rate_threshold' => 'min_hit_rate_threshold',
        'min_implied_probability_threshold' => 'min_implied_probability_threshold',
        'odds_format' => 'odds_format',
        'operator_ids' => 'operator_ids',
        'operator_keys' => 'operator_keys',
        'page' => 'page',
        'page_size' => 'page_size',
        'player_id' => 'player_id',
        'player_ids' => 'player_ids',
        'player_key' => 'player_key',
        'product_mode' => 'product_mode',
        'split_type' => 'split_type',
        'sport_id' => 'sport_id',
        'sport_ids' => 'sport_ids',
        'sport_key' => 'sport_key',
        'starting_soon' => 'starting_soon',
        'team_id' => 'team_id',
        'team_ids' => 'team_ids',
        'team_key' => 'team_key',
        'team_split' => 'team_split',
        'use_cartoon_images' => 'use_cartoon_images'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bet_type' => 'setBetType',
        'betting_market_category_id' => 'setBettingMarketCategoryId',
        'betting_market_category_ids' => 'setBettingMarketCategoryIds',
        'betting_market_entity_type' => 'setBettingMarketEntityType',
        'betting_market_ids' => 'setBettingMarketIds',
        'betting_market_position_id' => 'setBettingMarketPositionId',
        'betting_market_position_ids' => 'setBettingMarketPositionIds',
        'event_id' => 'setEventId',
        'event_ids' => 'setEventIds',
        'event_start_date_from' => 'setEventStartDateFrom',
        'event_start_date_to' => 'setEventStartDateTo',
        'fact_flow_type' => 'setFactFlowType',
        'flow_type' => 'setFlowType',
        'focus_entity_type_id' => 'setFocusEntityTypeId',
        'full_hit_rate' => 'setFullHitRate',
        'include_alt_lines' => 'setIncludeAltLines',
        'include_deeplinks' => 'setIncludeDeeplinks',
        'include_only_basic_trends' => 'setIncludeOnlyBasicTrends',
        'include_star_sign_content' => 'setIncludeStarSignContent',
        'league_id' => 'setLeagueId',
        'league_ids' => 'setLeagueIds',
        'league_key' => 'setLeagueKey',
        'likelihood_type' => 'setLikelihoodType',
        'max_hit_rate_threshold' => 'setMaxHitRateThreshold',
        'max_implied_probability_threshold' => 'setMaxImpliedProbabilityThreshold',
        'min_hit_rate_threshold' => 'setMinHitRateThreshold',
        'min_implied_probability_threshold' => 'setMinImpliedProbabilityThreshold',
        'odds_format' => 'setOddsFormat',
        'operator_ids' => 'setOperatorIds',
        'operator_keys' => 'setOperatorKeys',
        'page' => 'setPage',
        'page_size' => 'setPageSize',
        'player_id' => 'setPlayerId',
        'player_ids' => 'setPlayerIds',
        'player_key' => 'setPlayerKey',
        'product_mode' => 'setProductMode',
        'split_type' => 'setSplitType',
        'sport_id' => 'setSportId',
        'sport_ids' => 'setSportIds',
        'sport_key' => 'setSportKey',
        'starting_soon' => 'setStartingSoon',
        'team_id' => 'setTeamId',
        'team_ids' => 'setTeamIds',
        'team_key' => 'setTeamKey',
        'team_split' => 'setTeamSplit',
        'use_cartoon_images' => 'setUseCartoonImages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bet_type' => 'getBetType',
        'betting_market_category_id' => 'getBettingMarketCategoryId',
        'betting_market_category_ids' => 'getBettingMarketCategoryIds',
        'betting_market_entity_type' => 'getBettingMarketEntityType',
        'betting_market_ids' => 'getBettingMarketIds',
        'betting_market_position_id' => 'getBettingMarketPositionId',
        'betting_market_position_ids' => 'getBettingMarketPositionIds',
        'event_id' => 'getEventId',
        'event_ids' => 'getEventIds',
        'event_start_date_from' => 'getEventStartDateFrom',
        'event_start_date_to' => 'getEventStartDateTo',
        'fact_flow_type' => 'getFactFlowType',
        'flow_type' => 'getFlowType',
        'focus_entity_type_id' => 'getFocusEntityTypeId',
        'full_hit_rate' => 'getFullHitRate',
        'include_alt_lines' => 'getIncludeAltLines',
        'include_deeplinks' => 'getIncludeDeeplinks',
        'include_only_basic_trends' => 'getIncludeOnlyBasicTrends',
        'include_star_sign_content' => 'getIncludeStarSignContent',
        'league_id' => 'getLeagueId',
        'league_ids' => 'getLeagueIds',
        'league_key' => 'getLeagueKey',
        'likelihood_type' => 'getLikelihoodType',
        'max_hit_rate_threshold' => 'getMaxHitRateThreshold',
        'max_implied_probability_threshold' => 'getMaxImpliedProbabilityThreshold',
        'min_hit_rate_threshold' => 'getMinHitRateThreshold',
        'min_implied_probability_threshold' => 'getMinImpliedProbabilityThreshold',
        'odds_format' => 'getOddsFormat',
        'operator_ids' => 'getOperatorIds',
        'operator_keys' => 'getOperatorKeys',
        'page' => 'getPage',
        'page_size' => 'getPageSize',
        'player_id' => 'getPlayerId',
        'player_ids' => 'getPlayerIds',
        'player_key' => 'getPlayerKey',
        'product_mode' => 'getProductMode',
        'split_type' => 'getSplitType',
        'sport_id' => 'getSportId',
        'sport_ids' => 'getSportIds',
        'sport_key' => 'getSportKey',
        'starting_soon' => 'getStartingSoon',
        'team_id' => 'getTeamId',
        'team_ids' => 'getTeamIds',
        'team_key' => 'getTeamKey',
        'team_split' => 'getTeamSplit',
        'use_cartoon_images' => 'getUseCartoonImages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BET_TYPE_SINGLES = 'singles';
    public const BET_TYPE_PARLAY = 'parlay';
    public const BET_TYPE_SAME_GAME_PARLAY = 'same_game_parlay';
    public const BETTING_MARKET_ENTITY_TYPE_PLAYER = 'player';
    public const BETTING_MARKET_ENTITY_TYPE_TEAM = 'team';
    public const BETTING_MARKET_ENTITY_TYPE_EVENT = 'event';
    public const FACT_FLOW_TYPE_BASE = 'base';
    public const FACT_FLOW_TYPE_EXPANDED = 'expanded';
    public const FACT_FLOW_TYPE_MULTI = 'multi';
    public const FLOW_TYPE_FACT = 'fact';
    public const FLOW_TYPE_FUN = 'fun';
    public const FLOW_TYPE_PLAIN = 'plain';
    public const LIKELIHOOD_TYPE_LIKELY = 'likely';
    public const LIKELIHOOD_TYPE_POSSIBLE = 'possible';
    public const LIKELIHOOD_TYPE_LONGSHOT = 'longshot';
    public const ODDS_FORMAT_AMERICAN = 'american';
    public const ODDS_FORMAT_DECIMAL = 'decimal';
    public const ODDS_FORMAT_FRACTIONAL = 'fractional';
    public const ODDS_FORMAT_MULTIPLIER = 'multiplier';
    public const ODDS_FORMAT_PERCENT = 'percent';
    public const PRODUCT_MODE_SPORTSBOOK = 'sportsbook';
    public const PRODUCT_MODE_DFS = 'dfs';
    public const PRODUCT_MODE_PREDICTION_MARKET = 'prediction_market';
    public const SPLIT_TYPE_OVERS = 'overs';
    public const SPLIT_TYPE_UNDERS = 'unders';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBetTypeAllowableValues()
    {
        return [
            self::BET_TYPE_SINGLES,
            self::BET_TYPE_PARLAY,
            self::BET_TYPE_SAME_GAME_PARLAY,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBettingMarketEntityTypeAllowableValues()
    {
        return [
            self::BETTING_MARKET_ENTITY_TYPE_PLAYER,
            self::BETTING_MARKET_ENTITY_TYPE_TEAM,
            self::BETTING_MARKET_ENTITY_TYPE_EVENT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFactFlowTypeAllowableValues()
    {
        return [
            self::FACT_FLOW_TYPE_BASE,
            self::FACT_FLOW_TYPE_EXPANDED,
            self::FACT_FLOW_TYPE_MULTI,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFlowTypeAllowableValues()
    {
        return [
            self::FLOW_TYPE_FACT,
            self::FLOW_TYPE_FUN,
            self::FLOW_TYPE_PLAIN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLikelihoodTypeAllowableValues()
    {
        return [
            self::LIKELIHOOD_TYPE_LIKELY,
            self::LIKELIHOOD_TYPE_POSSIBLE,
            self::LIKELIHOOD_TYPE_LONGSHOT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOddsFormatAllowableValues()
    {
        return [
            self::ODDS_FORMAT_AMERICAN,
            self::ODDS_FORMAT_DECIMAL,
            self::ODDS_FORMAT_FRACTIONAL,
            self::ODDS_FORMAT_MULTIPLIER,
            self::ODDS_FORMAT_PERCENT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProductModeAllowableValues()
    {
        return [
            self::PRODUCT_MODE_SPORTSBOOK,
            self::PRODUCT_MODE_DFS,
            self::PRODUCT_MODE_PREDICTION_MARKET,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSplitTypeAllowableValues()
    {
        return [
            self::SPLIT_TYPE_OVERS,
            self::SPLIT_TYPE_UNDERS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('bet_type', $data ?? [], null);
        $this->setIfExists('betting_market_category_id', $data ?? [], null);
        $this->setIfExists('betting_market_category_ids', $data ?? [], null);
        $this->setIfExists('betting_market_entity_type', $data ?? [], null);
        $this->setIfExists('betting_market_ids', $data ?? [], null);
        $this->setIfExists('betting_market_position_id', $data ?? [], null);
        $this->setIfExists('betting_market_position_ids', $data ?? [], null);
        $this->setIfExists('event_id', $data ?? [], null);
        $this->setIfExists('event_ids', $data ?? [], null);
        $this->setIfExists('event_start_date_from', $data ?? [], null);
        $this->setIfExists('event_start_date_to', $data ?? [], null);
        $this->setIfExists('fact_flow_type', $data ?? [], null);
        $this->setIfExists('flow_type', $data ?? [], null);
        $this->setIfExists('focus_entity_type_id', $data ?? [], null);
        $this->setIfExists('full_hit_rate', $data ?? [], null);
        $this->setIfExists('include_alt_lines', $data ?? [], null);
        $this->setIfExists('include_deeplinks', $data ?? [], null);
        $this->setIfExists('include_only_basic_trends', $data ?? [], null);
        $this->setIfExists('include_star_sign_content', $data ?? [], null);
        $this->setIfExists('league_id', $data ?? [], null);
        $this->setIfExists('league_ids', $data ?? [], null);
        $this->setIfExists('league_key', $data ?? [], null);
        $this->setIfExists('likelihood_type', $data ?? [], null);
        $this->setIfExists('max_hit_rate_threshold', $data ?? [], null);
        $this->setIfExists('max_implied_probability_threshold', $data ?? [], null);
        $this->setIfExists('min_hit_rate_threshold', $data ?? [], null);
        $this->setIfExists('min_implied_probability_threshold', $data ?? [], null);
        $this->setIfExists('odds_format', $data ?? [], null);
        $this->setIfExists('operator_ids', $data ?? [], null);
        $this->setIfExists('operator_keys', $data ?? [], null);
        $this->setIfExists('page', $data ?? [], null);
        $this->setIfExists('page_size', $data ?? [], null);
        $this->setIfExists('player_id', $data ?? [], null);
        $this->setIfExists('player_ids', $data ?? [], null);
        $this->setIfExists('player_key', $data ?? [], null);
        $this->setIfExists('product_mode', $data ?? [], null);
        $this->setIfExists('split_type', $data ?? [], null);
        $this->setIfExists('sport_id', $data ?? [], null);
        $this->setIfExists('sport_ids', $data ?? [], null);
        $this->setIfExists('sport_key', $data ?? [], null);
        $this->setIfExists('starting_soon', $data ?? [], null);
        $this->setIfExists('team_id', $data ?? [], null);
        $this->setIfExists('team_ids', $data ?? [], null);
        $this->setIfExists('team_key', $data ?? [], null);
        $this->setIfExists('team_split', $data ?? [], null);
        $this->setIfExists('use_cartoon_images', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getBetTypeAllowableValues();
        if (!is_null($this->container['bet_type']) && !in_array($this->container['bet_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'bet_type', must be one of '%s'",
                $this->container['bet_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['betting_market_category_id']) && ($this->container['betting_market_category_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'betting_market_category_id', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getBettingMarketEntityTypeAllowableValues();
        if (!is_null($this->container['betting_market_entity_type']) && !in_array($this->container['betting_market_entity_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'betting_market_entity_type', must be one of '%s'",
                $this->container['betting_market_entity_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['betting_market_position_id']) && ($this->container['betting_market_position_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'betting_market_position_id', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['event_id']) && ($this->container['event_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'event_id', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getFactFlowTypeAllowableValues();
        if (!is_null($this->container['fact_flow_type']) && !in_array($this->container['fact_flow_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fact_flow_type', must be one of '%s'",
                $this->container['fact_flow_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFlowTypeAllowableValues();
        if (!is_null($this->container['flow_type']) && !in_array($this->container['flow_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'flow_type', must be one of '%s'",
                $this->container['flow_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['focus_entity_type_id']) && ($this->container['focus_entity_type_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'focus_entity_type_id', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['league_id']) && ($this->container['league_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'league_id', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getLikelihoodTypeAllowableValues();
        if (!is_null($this->container['likelihood_type']) && !in_array($this->container['likelihood_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'likelihood_type', must be one of '%s'",
                $this->container['likelihood_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['max_hit_rate_threshold']) && ($this->container['max_hit_rate_threshold'] > 100)) {
            $invalidProperties[] = "invalid value for 'max_hit_rate_threshold', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['max_hit_rate_threshold']) && ($this->container['max_hit_rate_threshold'] < 0)) {
            $invalidProperties[] = "invalid value for 'max_hit_rate_threshold', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['min_hit_rate_threshold']) && ($this->container['min_hit_rate_threshold'] > 100)) {
            $invalidProperties[] = "invalid value for 'min_hit_rate_threshold', must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['min_hit_rate_threshold']) && ($this->container['min_hit_rate_threshold'] < 0)) {
            $invalidProperties[] = "invalid value for 'min_hit_rate_threshold', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getOddsFormatAllowableValues();
        if (!is_null($this->container['odds_format']) && !in_array($this->container['odds_format'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'odds_format', must be one of '%s'",
                $this->container['odds_format'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['page']) && ($this->container['page'] < 1)) {
            $invalidProperties[] = "invalid value for 'page', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['page_size']) && ($this->container['page_size'] > 25)) {
            $invalidProperties[] = "invalid value for 'page_size', must be smaller than or equal to 25.";
        }

        if (!is_null($this->container['page_size']) && ($this->container['page_size'] < 1)) {
            $invalidProperties[] = "invalid value for 'page_size', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['player_id']) && ($this->container['player_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'player_id', must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getProductModeAllowableValues();
        if (!is_null($this->container['product_mode']) && !in_array($this->container['product_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'product_mode', must be one of '%s'",
                $this->container['product_mode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSplitTypeAllowableValues();
        if (!is_null($this->container['split_type']) && !in_array($this->container['split_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'split_type', must be one of '%s'",
                $this->container['split_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['sport_id']) && ($this->container['sport_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'sport_id', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['team_id']) && ($this->container['team_id'] < 1)) {
            $invalidProperties[] = "invalid value for 'team_id', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bet_type
     *
     * @return string|null
     */
    public function getBetType()
    {
        return $this->container['bet_type'];
    }

    /**
     * Sets bet_type
     *
     * @param string|null $bet_type Filter by bet type. If omitted, returns mixed singles and parlays.
     *
     * @return self
     */
    public function setBetType($bet_type)
    {
        if (is_null($bet_type)) {
            throw new \InvalidArgumentException('non-nullable bet_type cannot be null');
        }
        $allowedValues = $this->getBetTypeAllowableValues();
        if (!in_array($bet_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'bet_type', must be one of '%s'",
                    $bet_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['bet_type'] = $bet_type;

        return $this;
    }

    /**
     * Gets betting_market_category_id
     *
     * @return int|null
     * @deprecated
     */
    public function getBettingMarketCategoryId()
    {
        return $this->container['betting_market_category_id'];
    }

    /**
     * Sets betting_market_category_id
     *
     * @param int|null $betting_market_category_id Deprecated — use `betting_market_category_ids` instead (e.g. Shooting Props, Game Props etc.). A bare `betting_market_category_id` is treated as `betting_market_category_ids: [betting_market_category_id]`.
     *
     * @return self
     * @deprecated
     */
    public function setBettingMarketCategoryId($betting_market_category_id)
    {
        if (is_null($betting_market_category_id)) {
            throw new \InvalidArgumentException('non-nullable betting_market_category_id cannot be null');
        }

        if (($betting_market_category_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $betting_market_category_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['betting_market_category_id'] = $betting_market_category_id;

        return $this;
    }

    /**
     * Gets betting_market_category_ids
     *
     * @return int[]|null
     */
    public function getBettingMarketCategoryIds()
    {
        return $this->container['betting_market_category_ids'];
    }

    /**
     * Sets betting_market_category_ids
     *
     * @param int[]|null $betting_market_category_ids Filter by one or more betting market category IDs (e.g. Shooting Props, Game Props etc.). Empty array = no filter.
     *
     * @return self
     */
    public function setBettingMarketCategoryIds($betting_market_category_ids)
    {
        if (is_null($betting_market_category_ids)) {
            throw new \InvalidArgumentException('non-nullable betting_market_category_ids cannot be null');
        }
        $this->container['betting_market_category_ids'] = $betting_market_category_ids;

        return $this;
    }

    /**
     * Gets betting_market_entity_type
     *
     * @return string|null
     */
    public function getBettingMarketEntityType()
    {
        return $this->container['betting_market_entity_type'];
    }

    /**
     * Sets betting_market_entity_type
     *
     * @param string|null $betting_market_entity_type Filter by betting market entity type
     *
     * @return self
     */
    public function setBettingMarketEntityType($betting_market_entity_type)
    {
        if (is_null($betting_market_entity_type)) {
            throw new \InvalidArgumentException('non-nullable betting_market_entity_type cannot be null');
        }
        $allowedValues = $this->getBettingMarketEntityTypeAllowableValues();
        if (!in_array($betting_market_entity_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'betting_market_entity_type', must be one of '%s'",
                    $betting_market_entity_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['betting_market_entity_type'] = $betting_market_entity_type;

        return $this;
    }

    /**
     * Gets betting_market_ids
     *
     * @return int[]|null
     */
    public function getBettingMarketIds()
    {
        return $this->container['betting_market_ids'];
    }

    /**
     * Sets betting_market_ids
     *
     * @param int[]|null $betting_market_ids Filter by betting market IDs
     *
     * @return self
     */
    public function setBettingMarketIds($betting_market_ids)
    {
        if (is_null($betting_market_ids)) {
            throw new \InvalidArgumentException('non-nullable betting_market_ids cannot be null');
        }
        $this->container['betting_market_ids'] = $betting_market_ids;

        return $this;
    }

    /**
     * Gets betting_market_position_id
     *
     * @return int|null
     * @deprecated
     */
    public function getBettingMarketPositionId()
    {
        return $this->container['betting_market_position_id'];
    }

    /**
     * Sets betting_market_position_id
     *
     * @param int|null $betting_market_position_id Deprecated — use `betting_market_position_ids` instead. A bare `betting_market_position_id` is treated as `betting_market_position_ids: [betting_market_position_id]`.
     *
     * @return self
     * @deprecated
     */
    public function setBettingMarketPositionId($betting_market_position_id)
    {
        if (is_null($betting_market_position_id)) {
            throw new \InvalidArgumentException('non-nullable betting_market_position_id cannot be null');
        }

        if (($betting_market_position_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $betting_market_position_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['betting_market_position_id'] = $betting_market_position_id;

        return $this;
    }

    /**
     * Gets betting_market_position_ids
     *
     * @return int[]|null
     */
    public function getBettingMarketPositionIds()
    {
        return $this->container['betting_market_position_ids'];
    }

    /**
     * Sets betting_market_position_ids
     *
     * @param int[]|null $betting_market_position_ids Filter by one or more betting market position IDs. Empty array = no filter.
     *
     * @return self
     */
    public function setBettingMarketPositionIds($betting_market_position_ids)
    {
        if (is_null($betting_market_position_ids)) {
            throw new \InvalidArgumentException('non-nullable betting_market_position_ids cannot be null');
        }
        $this->container['betting_market_position_ids'] = $betting_market_position_ids;

        return $this;
    }

    /**
     * Gets event_id
     *
     * @return int|null
     * @deprecated
     */
    public function getEventId()
    {
        return $this->container['event_id'];
    }

    /**
     * Sets event_id
     *
     * @param int|null $event_id Deprecated — use `event_ids` instead. A bare `event_id` is treated as `event_ids: [event_id]`.
     *
     * @return self
     * @deprecated
     */
    public function setEventId($event_id)
    {
        if (is_null($event_id)) {
            throw new \InvalidArgumentException('non-nullable event_id cannot be null');
        }

        if (($event_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $event_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['event_id'] = $event_id;

        return $this;
    }

    /**
     * Gets event_ids
     *
     * @return int[]|null
     */
    public function getEventIds()
    {
        return $this->container['event_ids'];
    }

    /**
     * Sets event_ids
     *
     * @param int[]|null $event_ids Filter by one or more event IDs. Empty array = no filter.
     *
     * @return self
     */
    public function setEventIds($event_ids)
    {
        if (is_null($event_ids)) {
            throw new \InvalidArgumentException('non-nullable event_ids cannot be null');
        }
        $this->container['event_ids'] = $event_ids;

        return $this;
    }

    /**
     * Gets event_start_date_from
     *
     * @return \DateTime|null
     */
    public function getEventStartDateFrom()
    {
        return $this->container['event_start_date_from'];
    }

    /**
     * Sets event_start_date_from
     *
     * @param \DateTime|null $event_start_date_from Filter events starting on or after this value. Accepts a date ('2026-04-19') or full ISO 8601 timestamp ('2026-04-19T00:00:00Z').
     *
     * @return self
     */
    public function setEventStartDateFrom($event_start_date_from)
    {
        if (is_null($event_start_date_from)) {
            throw new \InvalidArgumentException('non-nullable event_start_date_from cannot be null');
        }
        $this->container['event_start_date_from'] = $event_start_date_from;

        return $this;
    }

    /**
     * Gets event_start_date_to
     *
     * @return \DateTime|null
     */
    public function getEventStartDateTo()
    {
        return $this->container['event_start_date_to'];
    }

    /**
     * Sets event_start_date_to
     *
     * @param \DateTime|null $event_start_date_to Filter events starting on or before this value. Accepts a date ('2026-04-26') or full ISO 8601 timestamp ('2026-04-26T23:59:59Z').
     *
     * @return self
     */
    public function setEventStartDateTo($event_start_date_to)
    {
        if (is_null($event_start_date_to)) {
            throw new \InvalidArgumentException('non-nullable event_start_date_to cannot be null');
        }
        $this->container['event_start_date_to'] = $event_start_date_to;

        return $this;
    }

    /**
     * Gets fact_flow_type
     *
     * @return string|null
     */
    public function getFactFlowType()
    {
        return $this->container['fact_flow_type'];
    }

    /**
     * Sets fact_flow_type
     *
     * @param string|null $fact_flow_type Sub-type for fact flows. Defaults to 'base' if omitted.
     *
     * @return self
     */
    public function setFactFlowType($fact_flow_type)
    {
        if (is_null($fact_flow_type)) {
            throw new \InvalidArgumentException('non-nullable fact_flow_type cannot be null');
        }
        $allowedValues = $this->getFactFlowTypeAllowableValues();
        if (!in_array($fact_flow_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fact_flow_type', must be one of '%s'",
                    $fact_flow_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fact_flow_type'] = $fact_flow_type;

        return $this;
    }

    /**
     * Gets flow_type
     *
     * @return string|null
     */
    public function getFlowType()
    {
        return $this->container['flow_type'];
    }

    /**
     * Sets flow_type
     *
     * @param string|null $flow_type Type of flow to return. 'plain' only returns parlays.
     *
     * @return self
     */
    public function setFlowType($flow_type)
    {
        if (is_null($flow_type)) {
            throw new \InvalidArgumentException('non-nullable flow_type cannot be null');
        }
        $allowedValues = $this->getFlowTypeAllowableValues();
        if (!in_array($flow_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'flow_type', must be one of '%s'",
                    $flow_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['flow_type'] = $flow_type;

        return $this;
    }

    /**
     * Gets focus_entity_type_id
     *
     * @return int|null
     */
    public function getFocusEntityTypeId()
    {
        return $this->container['focus_entity_type_id'];
    }

    /**
     * Sets focus_entity_type_id
     *
     * @param int|null $focus_entity_type_id Filter by focus entity type ID
     *
     * @return self
     */
    public function setFocusEntityTypeId($focus_entity_type_id)
    {
        if (is_null($focus_entity_type_id)) {
            throw new \InvalidArgumentException('non-nullable focus_entity_type_id cannot be null');
        }

        if (($focus_entity_type_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $focus_entity_type_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['focus_entity_type_id'] = $focus_entity_type_id;

        return $this;
    }

    /**
     * Gets full_hit_rate
     *
     * @return bool|null
     */
    public function getFullHitRate()
    {
        return $this->container['full_hit_rate'];
    }

    /**
     * Sets full_hit_rate
     *
     * @param bool|null $full_hit_rate When true, include full hit rate data in response
     *
     * @return self
     */
    public function setFullHitRate($full_hit_rate)
    {
        if (is_null($full_hit_rate)) {
            throw new \InvalidArgumentException('non-nullable full_hit_rate cannot be null');
        }
        $this->container['full_hit_rate'] = $full_hit_rate;

        return $this;
    }

    /**
     * Gets include_alt_lines
     *
     * @return bool|null
     */
    public function getIncludeAltLines()
    {
        return $this->container['include_alt_lines'];
    }

    /**
     * Sets include_alt_lines
     *
     * @param bool|null $include_alt_lines When false, exclude alt lines. Defaults to true.
     *
     * @return self
     */
    public function setIncludeAltLines($include_alt_lines)
    {
        if (is_null($include_alt_lines)) {
            throw new \InvalidArgumentException('non-nullable include_alt_lines cannot be null');
        }
        $this->container['include_alt_lines'] = $include_alt_lines;

        return $this;
    }

    /**
     * Gets include_deeplinks
     *
     * @return bool|null
     */
    public function getIncludeDeeplinks()
    {
        return $this->container['include_deeplinks'];
    }

    /**
     * Sets include_deeplinks
     *
     * @param bool|null $include_deeplinks When true, returns operator-specific odds and deeplink URLs (bet_ios_deep_link_url, bet_android_deep_link_url, bet_web_deep_link_url) for each flow. Requires exactly one operator_id in operator_ids.
     *
     * @return self
     */
    public function setIncludeDeeplinks($include_deeplinks)
    {
        if (is_null($include_deeplinks)) {
            throw new \InvalidArgumentException('non-nullable include_deeplinks cannot be null');
        }
        $this->container['include_deeplinks'] = $include_deeplinks;

        return $this;
    }

    /**
     * Gets include_only_basic_trends
     *
     * @return bool|null
     */
    public function getIncludeOnlyBasicTrends()
    {
        return $this->container['include_only_basic_trends'];
    }

    /**
     * Sets include_only_basic_trends
     *
     * @param bool|null $include_only_basic_trends When true, return only basic trends (omit fact flows with conditions)
     *
     * @return self
     */
    public function setIncludeOnlyBasicTrends($include_only_basic_trends)
    {
        if (is_null($include_only_basic_trends)) {
            throw new \InvalidArgumentException('non-nullable include_only_basic_trends cannot be null');
        }
        $this->container['include_only_basic_trends'] = $include_only_basic_trends;

        return $this;
    }

    /**
     * Gets include_star_sign_content
     *
     * @return bool|null
     */
    public function getIncludeStarSignContent()
    {
        return $this->container['include_star_sign_content'];
    }

    /**
     * Sets include_star_sign_content
     *
     * @param bool|null $include_star_sign_content When true, include star sign/horoscope content in flows
     *
     * @return self
     */
    public function setIncludeStarSignContent($include_star_sign_content)
    {
        if (is_null($include_star_sign_content)) {
            throw new \InvalidArgumentException('non-nullable include_star_sign_content cannot be null');
        }
        $this->container['include_star_sign_content'] = $include_star_sign_content;

        return $this;
    }

    /**
     * Gets league_id
     *
     * @return int|null
     * @deprecated
     */
    public function getLeagueId()
    {
        return $this->container['league_id'];
    }

    /**
     * Sets league_id
     *
     * @param int|null $league_id Deprecated — use `league_ids` instead. A bare `league_id` is treated as `league_ids: [league_id]`.
     *
     * @return self
     * @deprecated
     */
    public function setLeagueId($league_id)
    {
        if (is_null($league_id)) {
            throw new \InvalidArgumentException('non-nullable league_id cannot be null');
        }

        if (($league_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $league_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['league_id'] = $league_id;

        return $this;
    }

    /**
     * Gets league_ids
     *
     * @return int[]|null
     */
    public function getLeagueIds()
    {
        return $this->container['league_ids'];
    }

    /**
     * Sets league_ids
     *
     * @param int[]|null $league_ids Filter by one or more league IDs. Empty array = no filter.
     *
     * @return self
     */
    public function setLeagueIds($league_ids)
    {
        if (is_null($league_ids)) {
            throw new \InvalidArgumentException('non-nullable league_ids cannot be null');
        }
        $this->container['league_ids'] = $league_ids;

        return $this;
    }

    /**
     * Gets league_key
     *
     * @return string|null
     */
    public function getLeagueKey()
    {
        return $this->container['league_key'];
    }

    /**
     * Sets league_key
     *
     * @param string|null $league_key League external key (e.g. 'nba', 'united-states.nba'). Format: {league_key} or {country_key}.{league_key}. Alternative to league_id. If both are provided, league_id takes precedence.
     *
     * @return self
     */
    public function setLeagueKey($league_key)
    {
        if (is_null($league_key)) {
            throw new \InvalidArgumentException('non-nullable league_key cannot be null');
        }
        $this->container['league_key'] = $league_key;

        return $this;
    }

    /**
     * Gets likelihood_type
     *
     * @return string|null
     */
    public function getLikelihoodType()
    {
        return $this->container['likelihood_type'];
    }

    /**
     * Sets likelihood_type
     *
     * @param string|null $likelihood_type Filter by likelihood category
     *
     * @return self
     */
    public function setLikelihoodType($likelihood_type)
    {
        if (is_null($likelihood_type)) {
            throw new \InvalidArgumentException('non-nullable likelihood_type cannot be null');
        }
        $allowedValues = $this->getLikelihoodTypeAllowableValues();
        if (!in_array($likelihood_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'likelihood_type', must be one of '%s'",
                    $likelihood_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['likelihood_type'] = $likelihood_type;

        return $this;
    }

    /**
     * Gets max_hit_rate_threshold
     *
     * @return int|null
     */
    public function getMaxHitRateThreshold()
    {
        return $this->container['max_hit_rate_threshold'];
    }

    /**
     * Sets max_hit_rate_threshold
     *
     * @param int|null $max_hit_rate_threshold Maximum hit rate threshold filter (0-100)
     *
     * @return self
     */
    public function setMaxHitRateThreshold($max_hit_rate_threshold)
    {
        if (is_null($max_hit_rate_threshold)) {
            throw new \InvalidArgumentException('non-nullable max_hit_rate_threshold cannot be null');
        }

        if (($max_hit_rate_threshold > 100)) {
            throw new \InvalidArgumentException('invalid value for $max_hit_rate_threshold when calling V1TrendsFlowsPostRequest., must be smaller than or equal to 100.');
        }
        if (($max_hit_rate_threshold < 0)) {
            throw new \InvalidArgumentException('invalid value for $max_hit_rate_threshold when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 0.');
        }

        $this->container['max_hit_rate_threshold'] = $max_hit_rate_threshold;

        return $this;
    }

    /**
     * Gets max_implied_probability_threshold
     *
     * @return float|null
     */
    public function getMaxImpliedProbabilityThreshold()
    {
        return $this->container['max_implied_probability_threshold'];
    }

    /**
     * Sets max_implied_probability_threshold
     *
     * @param float|null $max_implied_probability_threshold Maximum implied probability threshold filter
     *
     * @return self
     */
    public function setMaxImpliedProbabilityThreshold($max_implied_probability_threshold)
    {
        if (is_null($max_implied_probability_threshold)) {
            throw new \InvalidArgumentException('non-nullable max_implied_probability_threshold cannot be null');
        }
        $this->container['max_implied_probability_threshold'] = $max_implied_probability_threshold;

        return $this;
    }

    /**
     * Gets min_hit_rate_threshold
     *
     * @return int|null
     */
    public function getMinHitRateThreshold()
    {
        return $this->container['min_hit_rate_threshold'];
    }

    /**
     * Sets min_hit_rate_threshold
     *
     * @param int|null $min_hit_rate_threshold Minimum hit rate threshold filter (0-100)
     *
     * @return self
     */
    public function setMinHitRateThreshold($min_hit_rate_threshold)
    {
        if (is_null($min_hit_rate_threshold)) {
            throw new \InvalidArgumentException('non-nullable min_hit_rate_threshold cannot be null');
        }

        if (($min_hit_rate_threshold > 100)) {
            throw new \InvalidArgumentException('invalid value for $min_hit_rate_threshold when calling V1TrendsFlowsPostRequest., must be smaller than or equal to 100.');
        }
        if (($min_hit_rate_threshold < 0)) {
            throw new \InvalidArgumentException('invalid value for $min_hit_rate_threshold when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 0.');
        }

        $this->container['min_hit_rate_threshold'] = $min_hit_rate_threshold;

        return $this;
    }

    /**
     * Gets min_implied_probability_threshold
     *
     * @return float|null
     */
    public function getMinImpliedProbabilityThreshold()
    {
        return $this->container['min_implied_probability_threshold'];
    }

    /**
     * Sets min_implied_probability_threshold
     *
     * @param float|null $min_implied_probability_threshold Minimum implied probability threshold filter
     *
     * @return self
     */
    public function setMinImpliedProbabilityThreshold($min_implied_probability_threshold)
    {
        if (is_null($min_implied_probability_threshold)) {
            throw new \InvalidArgumentException('non-nullable min_implied_probability_threshold cannot be null');
        }
        $this->container['min_implied_probability_threshold'] = $min_implied_probability_threshold;

        return $this;
    }

    /**
     * Gets odds_format
     *
     * @return string|null
     */
    public function getOddsFormat()
    {
        return $this->container['odds_format'];
    }

    /**
     * Sets odds_format
     *
     * @param string|null $odds_format Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
     *
     * @return self
     */
    public function setOddsFormat($odds_format)
    {
        if (is_null($odds_format)) {
            throw new \InvalidArgumentException('non-nullable odds_format cannot be null');
        }
        $allowedValues = $this->getOddsFormatAllowableValues();
        if (!in_array($odds_format, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'odds_format', must be one of '%s'",
                    $odds_format,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['odds_format'] = $odds_format;

        return $this;
    }

    /**
     * Gets operator_ids
     *
     * @return int[]|null
     */
    public function getOperatorIds()
    {
        return $this->container['operator_ids'];
    }

    /**
     * Sets operator_ids
     *
     * @param int[]|null $operator_ids Filter by operator IDs
     *
     * @return self
     */
    public function setOperatorIds($operator_ids)
    {
        if (is_null($operator_ids)) {
            throw new \InvalidArgumentException('non-nullable operator_ids cannot be null');
        }
        $this->container['operator_ids'] = $operator_ids;

        return $this;
    }

    /**
     * Gets operator_keys
     *
     * @return string[]|null
     */
    public function getOperatorKeys()
    {
        return $this->container['operator_keys'];
    }

    /**
     * Sets operator_keys
     *
     * @param string[]|null $operator_keys Filter by operator external keys (e.g. 'draftkings'). Format: {operator_key}. Resolved IDs are merged with operator_ids.
     *
     * @return self
     */
    public function setOperatorKeys($operator_keys)
    {
        if (is_null($operator_keys)) {
            throw new \InvalidArgumentException('non-nullable operator_keys cannot be null');
        }
        $this->container['operator_keys'] = $operator_keys;

        return $this;
    }

    /**
     * Gets page
     *
     * @return int|null
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param int|null $page page
     *
     * @return self
     */
    public function setPage($page)
    {
        if (is_null($page)) {
            throw new \InvalidArgumentException('non-nullable page cannot be null');
        }

        if (($page < 1)) {
            throw new \InvalidArgumentException('invalid value for $page when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['page'] = $page;

        return $this;
    }

    /**
     * Gets page_size
     *
     * @return int|null
     */
    public function getPageSize()
    {
        return $this->container['page_size'];
    }

    /**
     * Sets page_size
     *
     * @param int|null $page_size page_size
     *
     * @return self
     */
    public function setPageSize($page_size)
    {
        if (is_null($page_size)) {
            throw new \InvalidArgumentException('non-nullable page_size cannot be null');
        }

        if (($page_size > 25)) {
            throw new \InvalidArgumentException('invalid value for $page_size when calling V1TrendsFlowsPostRequest., must be smaller than or equal to 25.');
        }
        if (($page_size < 1)) {
            throw new \InvalidArgumentException('invalid value for $page_size when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['page_size'] = $page_size;

        return $this;
    }

    /**
     * Gets player_id
     *
     * @return int|null
     * @deprecated
     */
    public function getPlayerId()
    {
        return $this->container['player_id'];
    }

    /**
     * Sets player_id
     *
     * @param int|null $player_id Deprecated — use `player_ids` instead. A bare `player_id` is treated as `player_ids: [player_id]`.
     *
     * @return self
     * @deprecated
     */
    public function setPlayerId($player_id)
    {
        if (is_null($player_id)) {
            throw new \InvalidArgumentException('non-nullable player_id cannot be null');
        }

        if (($player_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $player_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['player_id'] = $player_id;

        return $this;
    }

    /**
     * Gets player_ids
     *
     * @return int[]|null
     */
    public function getPlayerIds()
    {
        return $this->container['player_ids'];
    }

    /**
     * Sets player_ids
     *
     * @param int[]|null $player_ids Filter by one or more player IDs. Empty array = no filter.
     *
     * @return self
     */
    public function setPlayerIds($player_ids)
    {
        if (is_null($player_ids)) {
            throw new \InvalidArgumentException('non-nullable player_ids cannot be null');
        }
        $this->container['player_ids'] = $player_ids;

        return $this;
    }

    /**
     * Gets player_key
     *
     * @return string|null
     */
    public function getPlayerKey()
    {
        return $this->container['player_key'];
    }

    /**
     * Sets player_key
     *
     * @param string|null $player_key Player external key (e.g. 'nikola-vucevic', 'chicago-bulls.tre-jones', 'nba.boston-celtics.nikola-vucevic'). Format: {player_key} or {team_key}.{player_key} or {league_key}.{team_key}.{player_key}. Alternative to player_id. If both are provided, player_id takes precedence.
     *
     * @return self
     */
    public function setPlayerKey($player_key)
    {
        if (is_null($player_key)) {
            throw new \InvalidArgumentException('non-nullable player_key cannot be null');
        }
        $this->container['player_key'] = $player_key;

        return $this;
    }

    /**
     * Gets product_mode
     *
     * @return string|null
     */
    public function getProductMode()
    {
        return $this->container['product_mode'];
    }

    /**
     * Sets product_mode
     *
     * @param string|null $product_mode Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
     *
     * @return self
     */
    public function setProductMode($product_mode)
    {
        if (is_null($product_mode)) {
            throw new \InvalidArgumentException('non-nullable product_mode cannot be null');
        }
        $allowedValues = $this->getProductModeAllowableValues();
        if (!in_array($product_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'product_mode', must be one of '%s'",
                    $product_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['product_mode'] = $product_mode;

        return $this;
    }

    /**
     * Gets split_type
     *
     * @return string|null
     */
    public function getSplitType()
    {
        return $this->container['split_type'];
    }

    /**
     * Sets split_type
     *
     * @param string|null $split_type Filter by split type (overs or unders)
     *
     * @return self
     */
    public function setSplitType($split_type)
    {
        if (is_null($split_type)) {
            throw new \InvalidArgumentException('non-nullable split_type cannot be null');
        }
        $allowedValues = $this->getSplitTypeAllowableValues();
        if (!in_array($split_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'split_type', must be one of '%s'",
                    $split_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['split_type'] = $split_type;

        return $this;
    }

    /**
     * Gets sport_id
     *
     * @return int|null
     * @deprecated
     */
    public function getSportId()
    {
        return $this->container['sport_id'];
    }

    /**
     * Sets sport_id
     *
     * @param int|null $sport_id Deprecated — use `sport_ids` instead. A bare `sport_id` is treated as `sport_ids: [sport_id]`.
     *
     * @return self
     * @deprecated
     */
    public function setSportId($sport_id)
    {
        if (is_null($sport_id)) {
            throw new \InvalidArgumentException('non-nullable sport_id cannot be null');
        }

        if (($sport_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $sport_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['sport_id'] = $sport_id;

        return $this;
    }

    /**
     * Gets sport_ids
     *
     * @return int[]|null
     */
    public function getSportIds()
    {
        return $this->container['sport_ids'];
    }

    /**
     * Sets sport_ids
     *
     * @param int[]|null $sport_ids Filter by one or more sport IDs. Empty array = no filter.
     *
     * @return self
     */
    public function setSportIds($sport_ids)
    {
        if (is_null($sport_ids)) {
            throw new \InvalidArgumentException('non-nullable sport_ids cannot be null');
        }
        $this->container['sport_ids'] = $sport_ids;

        return $this;
    }

    /**
     * Gets sport_key
     *
     * @return string|null
     */
    public function getSportKey()
    {
        return $this->container['sport_key'];
    }

    /**
     * Sets sport_key
     *
     * @param string|null $sport_key Sport external key (e.g. 'american-football'). Format: {sport_key}. Alternative to sport_id. If both are provided, sport_id takes precedence.
     *
     * @return self
     */
    public function setSportKey($sport_key)
    {
        if (is_null($sport_key)) {
            throw new \InvalidArgumentException('non-nullable sport_key cannot be null');
        }
        $this->container['sport_key'] = $sport_key;

        return $this;
    }

    /**
     * Gets starting_soon
     *
     * @return bool|null
     */
    public function getStartingSoon()
    {
        return $this->container['starting_soon'];
    }

    /**
     * Sets starting_soon
     *
     * @param bool|null $starting_soon When true, only return flows for events starting soon
     *
     * @return self
     */
    public function setStartingSoon($starting_soon)
    {
        if (is_null($starting_soon)) {
            throw new \InvalidArgumentException('non-nullable starting_soon cannot be null');
        }
        $this->container['starting_soon'] = $starting_soon;

        return $this;
    }

    /**
     * Gets team_id
     *
     * @return int|null
     * @deprecated
     */
    public function getTeamId()
    {
        return $this->container['team_id'];
    }

    /**
     * Sets team_id
     *
     * @param int|null $team_id Deprecated — use `team_ids` instead. A bare `team_id` is treated as `team_ids: [team_id]`.
     *
     * @return self
     * @deprecated
     */
    public function setTeamId($team_id)
    {
        if (is_null($team_id)) {
            throw new \InvalidArgumentException('non-nullable team_id cannot be null');
        }

        if (($team_id < 1)) {
            throw new \InvalidArgumentException('invalid value for $team_id when calling V1TrendsFlowsPostRequest., must be bigger than or equal to 1.');
        }

        $this->container['team_id'] = $team_id;

        return $this;
    }

    /**
     * Gets team_ids
     *
     * @return int[]|null
     */
    public function getTeamIds()
    {
        return $this->container['team_ids'];
    }

    /**
     * Sets team_ids
     *
     * @param int[]|null $team_ids Filter by one or more team IDs. Empty array = no filter.
     *
     * @return self
     */
    public function setTeamIds($team_ids)
    {
        if (is_null($team_ids)) {
            throw new \InvalidArgumentException('non-nullable team_ids cannot be null');
        }
        $this->container['team_ids'] = $team_ids;

        return $this;
    }

    /**
     * Gets team_key
     *
     * @return string|null
     */
    public function getTeamKey()
    {
        return $this->container['team_key'];
    }

    /**
     * Sets team_key
     *
     * @param string|null $team_key Team external key (e.g. 'new-england-patriots', 'nfl.new-england-patriots'). Format: {team_key} or {league_key}.{team_key}. Alternative to team_id. If both are provided, team_id takes precedence.
     *
     * @return self
     */
    public function setTeamKey($team_key)
    {
        if (is_null($team_key)) {
            throw new \InvalidArgumentException('non-nullable team_key cannot be null');
        }
        $this->container['team_key'] = $team_key;

        return $this;
    }

    /**
     * Gets team_split
     *
     * @return string|null
     */
    public function getTeamSplit()
    {
        return $this->container['team_split'];
    }

    /**
     * Sets team_split
     *
     * @param string|null $team_split Team split filter value
     *
     * @return self
     */
    public function setTeamSplit($team_split)
    {
        if (is_null($team_split)) {
            throw new \InvalidArgumentException('non-nullable team_split cannot be null');
        }
        $this->container['team_split'] = $team_split;

        return $this;
    }

    /**
     * Gets use_cartoon_images
     *
     * @return bool|null
     */
    public function getUseCartoonImages()
    {
        return $this->container['use_cartoon_images'];
    }

    /**
     * Sets use_cartoon_images
     *
     * @param bool|null $use_cartoon_images When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
     *
     * @return self
     */
    public function setUseCartoonImages($use_cartoon_images)
    {
        if (is_null($use_cartoon_images)) {
            throw new \InvalidArgumentException('non-nullable use_cartoon_images cannot be null');
        }
        $this->container['use_cartoon_images'] = $use_cartoon_images;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


