<?php
/**
 * V1TrendsByBettingMarketPositionPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * V1TrendsByBettingMarketPositionPostRequest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1TrendsByBettingMarketPositionPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_v1_trends_by_betting_market_position_post_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'event_betting_market_position_ids' => 'int[]',
        'odds_format' => 'string',
        'product_mode' => 'string',
        'use_cartoon_images' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'event_betting_market_position_ids' => 'int64',
        'odds_format' => null,
        'product_mode' => null,
        'use_cartoon_images' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'event_betting_market_position_ids' => false,
        'odds_format' => false,
        'product_mode' => false,
        'use_cartoon_images' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'event_betting_market_position_ids' => 'event_betting_market_position_ids',
        'odds_format' => 'odds_format',
        'product_mode' => 'product_mode',
        'use_cartoon_images' => 'use_cartoon_images'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'event_betting_market_position_ids' => 'setEventBettingMarketPositionIds',
        'odds_format' => 'setOddsFormat',
        'product_mode' => 'setProductMode',
        'use_cartoon_images' => 'setUseCartoonImages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'event_betting_market_position_ids' => 'getEventBettingMarketPositionIds',
        'odds_format' => 'getOddsFormat',
        'product_mode' => 'getProductMode',
        'use_cartoon_images' => 'getUseCartoonImages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ODDS_FORMAT_AMERICAN = 'american';
    public const ODDS_FORMAT_DECIMAL = 'decimal';
    public const ODDS_FORMAT_FRACTIONAL = 'fractional';
    public const ODDS_FORMAT_MULTIPLIER = 'multiplier';
    public const ODDS_FORMAT_PERCENT = 'percent';
    public const PRODUCT_MODE_SPORTSBOOK = 'sportsbook';
    public const PRODUCT_MODE_DFS = 'dfs';
    public const PRODUCT_MODE_PREDICTION_MARKET = 'prediction_market';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOddsFormatAllowableValues()
    {
        return [
            self::ODDS_FORMAT_AMERICAN,
            self::ODDS_FORMAT_DECIMAL,
            self::ODDS_FORMAT_FRACTIONAL,
            self::ODDS_FORMAT_MULTIPLIER,
            self::ODDS_FORMAT_PERCENT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getProductModeAllowableValues()
    {
        return [
            self::PRODUCT_MODE_SPORTSBOOK,
            self::PRODUCT_MODE_DFS,
            self::PRODUCT_MODE_PREDICTION_MARKET,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('event_betting_market_position_ids', $data ?? [], null);
        $this->setIfExists('odds_format', $data ?? [], null);
        $this->setIfExists('product_mode', $data ?? [], null);
        $this->setIfExists('use_cartoon_images', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['event_betting_market_position_ids'] === null) {
            $invalidProperties[] = "'event_betting_market_position_ids' can't be null";
        }
        if ((count($this->container['event_betting_market_position_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'event_betting_market_position_ids', number of items must be greater than or equal to 1.";
        }

        $allowedValues = $this->getOddsFormatAllowableValues();
        if (!is_null($this->container['odds_format']) && !in_array($this->container['odds_format'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'odds_format', must be one of '%s'",
                $this->container['odds_format'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getProductModeAllowableValues();
        if (!is_null($this->container['product_mode']) && !in_array($this->container['product_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'product_mode', must be one of '%s'",
                $this->container['product_mode'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets event_betting_market_position_ids
     *
     * @return int[]
     */
    public function getEventBettingMarketPositionIds()
    {
        return $this->container['event_betting_market_position_ids'];
    }

    /**
     * Sets event_betting_market_position_ids
     *
     * @param int[] $event_betting_market_position_ids Array of event betting market position IDs
     *
     * @return self
     */
    public function setEventBettingMarketPositionIds($event_betting_market_position_ids)
    {
        if (is_null($event_betting_market_position_ids)) {
            throw new \InvalidArgumentException('non-nullable event_betting_market_position_ids cannot be null');
        }


        if ((count($event_betting_market_position_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $event_betting_market_position_ids when calling V1TrendsByBettingMarketPositionPostRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['event_betting_market_position_ids'] = $event_betting_market_position_ids;

        return $this;
    }

    /**
     * Gets odds_format
     *
     * @return string|null
     */
    public function getOddsFormat()
    {
        return $this->container['odds_format'];
    }

    /**
     * Sets odds_format
     *
     * @param string|null $odds_format Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
     *
     * @return self
     */
    public function setOddsFormat($odds_format)
    {
        if (is_null($odds_format)) {
            throw new \InvalidArgumentException('non-nullable odds_format cannot be null');
        }
        $allowedValues = $this->getOddsFormatAllowableValues();
        if (!in_array($odds_format, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'odds_format', must be one of '%s'",
                    $odds_format,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['odds_format'] = $odds_format;

        return $this;
    }

    /**
     * Gets product_mode
     *
     * @return string|null
     */
    public function getProductMode()
    {
        return $this->container['product_mode'];
    }

    /**
     * Sets product_mode
     *
     * @param string|null $product_mode Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
     *
     * @return self
     */
    public function setProductMode($product_mode)
    {
        if (is_null($product_mode)) {
            throw new \InvalidArgumentException('non-nullable product_mode cannot be null');
        }
        $allowedValues = $this->getProductModeAllowableValues();
        if (!in_array($product_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'product_mode', must be one of '%s'",
                    $product_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['product_mode'] = $product_mode;

        return $this;
    }

    /**
     * Gets use_cartoon_images
     *
     * @return bool|null
     */
    public function getUseCartoonImages()
    {
        return $this->container['use_cartoon_images'];
    }

    /**
     * Sets use_cartoon_images
     *
     * @param bool|null $use_cartoon_images When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
     *
     * @return self
     */
    public function setUseCartoonImages($use_cartoon_images)
    {
        if (is_null($use_cartoon_images)) {
            throw new \InvalidArgumentException('non-nullable use_cartoon_images cannot be null');
        }
        $this->container['use_cartoon_images'] = $use_cartoon_images;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


