<?php
/**
 * V1TrendsFlowsByIdPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Model;

use \ArrayAccess;
use \Odditt\ApiClient\ObjectSerializer;

/**
 * V1TrendsFlowsByIdPostRequest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class V1TrendsFlowsByIdPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = '_v1_trends_flows_by_id_post_request';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'fact_flow_type' => 'string',
        'flow_ids' => 'int[]',
        'flow_type' => 'string',
        'use_cartoon_images' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'fact_flow_type' => null,
        'flow_ids' => 'int64',
        'flow_type' => null,
        'use_cartoon_images' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'fact_flow_type' => false,
        'flow_ids' => false,
        'flow_type' => false,
        'use_cartoon_images' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fact_flow_type' => 'fact_flow_type',
        'flow_ids' => 'flow_ids',
        'flow_type' => 'flow_type',
        'use_cartoon_images' => 'use_cartoon_images'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fact_flow_type' => 'setFactFlowType',
        'flow_ids' => 'setFlowIds',
        'flow_type' => 'setFlowType',
        'use_cartoon_images' => 'setUseCartoonImages'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fact_flow_type' => 'getFactFlowType',
        'flow_ids' => 'getFlowIds',
        'flow_type' => 'getFlowType',
        'use_cartoon_images' => 'getUseCartoonImages'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FACT_FLOW_TYPE_BASE = 'base';
    public const FACT_FLOW_TYPE_EXPANDED = 'expanded';
    public const FLOW_TYPE_FACT_FLOW = 'fact_flow';
    public const FLOW_TYPE_FUN_FLOW = 'fun_flow';
    public const FLOW_TYPE_FACT_FLOW_PARLAY = 'fact_flow_parlay';
    public const FLOW_TYPE_FUN_FLOW_PARLAY = 'fun_flow_parlay';
    public const FLOW_TYPE_PLAIN_FLOW_PARLAY = 'plain_flow_parlay';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFactFlowTypeAllowableValues()
    {
        return [
            self::FACT_FLOW_TYPE_BASE,
            self::FACT_FLOW_TYPE_EXPANDED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFlowTypeAllowableValues()
    {
        return [
            self::FLOW_TYPE_FACT_FLOW,
            self::FLOW_TYPE_FUN_FLOW,
            self::FLOW_TYPE_FACT_FLOW_PARLAY,
            self::FLOW_TYPE_FUN_FLOW_PARLAY,
            self::FLOW_TYPE_PLAIN_FLOW_PARLAY,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fact_flow_type', $data ?? [], null);
        $this->setIfExists('flow_ids', $data ?? [], null);
        $this->setIfExists('flow_type', $data ?? [], null);
        $this->setIfExists('use_cartoon_images', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getFactFlowTypeAllowableValues();
        if (!is_null($this->container['fact_flow_type']) && !in_array($this->container['fact_flow_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'fact_flow_type', must be one of '%s'",
                $this->container['fact_flow_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['flow_ids'] === null) {
            $invalidProperties[] = "'flow_ids' can't be null";
        }
        if ((count($this->container['flow_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'flow_ids', number of items must be greater than or equal to 1.";
        }

        if ($this->container['flow_type'] === null) {
            $invalidProperties[] = "'flow_type' can't be null";
        }
        $allowedValues = $this->getFlowTypeAllowableValues();
        if (!is_null($this->container['flow_type']) && !in_array($this->container['flow_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'flow_type', must be one of '%s'",
                $this->container['flow_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fact_flow_type
     *
     * @return string|null
     */
    public function getFactFlowType()
    {
        return $this->container['fact_flow_type'];
    }

    /**
     * Sets fact_flow_type
     *
     * @param string|null $fact_flow_type Sub-type for fact flows. Defaults to 'base' if omitted.
     *
     * @return self
     */
    public function setFactFlowType($fact_flow_type)
    {
        if (is_null($fact_flow_type)) {
            throw new \InvalidArgumentException('non-nullable fact_flow_type cannot be null');
        }
        $allowedValues = $this->getFactFlowTypeAllowableValues();
        if (!in_array($fact_flow_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'fact_flow_type', must be one of '%s'",
                    $fact_flow_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['fact_flow_type'] = $fact_flow_type;

        return $this;
    }

    /**
     * Gets flow_ids
     *
     * @return int[]
     */
    public function getFlowIds()
    {
        return $this->container['flow_ids'];
    }

    /**
     * Sets flow_ids
     *
     * @param int[] $flow_ids Array of flow IDs to retrieve
     *
     * @return self
     */
    public function setFlowIds($flow_ids)
    {
        if (is_null($flow_ids)) {
            throw new \InvalidArgumentException('non-nullable flow_ids cannot be null');
        }


        if ((count($flow_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $flow_ids when calling V1TrendsFlowsByIdPostRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['flow_ids'] = $flow_ids;

        return $this;
    }

    /**
     * Gets flow_type
     *
     * @return string
     */
    public function getFlowType()
    {
        return $this->container['flow_type'];
    }

    /**
     * Sets flow_type
     *
     * @param string $flow_type flow_type
     *
     * @return self
     */
    public function setFlowType($flow_type)
    {
        if (is_null($flow_type)) {
            throw new \InvalidArgumentException('non-nullable flow_type cannot be null');
        }
        $allowedValues = $this->getFlowTypeAllowableValues();
        if (!in_array($flow_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'flow_type', must be one of '%s'",
                    $flow_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['flow_type'] = $flow_type;

        return $this;
    }

    /**
     * Gets use_cartoon_images
     *
     * @return bool|null
     */
    public function getUseCartoonImages()
    {
        return $this->container['use_cartoon_images'];
    }

    /**
     * Sets use_cartoon_images
     *
     * @param bool|null $use_cartoon_images When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
     *
     * @return self
     */
    public function setUseCartoonImages($use_cartoon_images)
    {
        if (is_null($use_cartoon_images)) {
            throw new \InvalidArgumentException('non-nullable use_cartoon_images cannot be null');
        }
        $this->container['use_cartoon_images'] = $use_cartoon_images;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


