<?php
/**
 * HistoricalApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Odditt\ApiClient\ApiException;
use Odditt\ApiClient\Configuration;
use Odditt\ApiClient\FormDataProcessor;
use Odditt\ApiClient\HeaderSelector;
use Odditt\ApiClient\ObjectSerializer;

/**
 * HistoricalApi Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HistoricalApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1HistoricalEventsGet' => [
            'application/json',
        ],
        'v1HistoricalOddsEventIdExtGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1HistoricalEventsGet
     *
     * List historical odds events (paginated)
     *
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to 'v1')
     * @param  int|null $sport_id sport_id (optional)
     * @param  int|null $league_id league_id (optional)
     * @param  int|null $team_id Filter to events involving this team as either home or away. (optional)
     * @param  string|null $start_date Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  string|null $end_date Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $page_size page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalEventsGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse
     */
    public function v1HistoricalEventsGet($schema_version = 'v1', $sport_id = null, $league_id = null, $team_id = null, $start_date = null, $end_date = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1HistoricalEventsGet'][0])
    {
        list($response) = $this->v1HistoricalEventsGetWithHttpInfo($schema_version, $sport_id, $league_id, $team_id, $start_date, $end_date, $page, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation v1HistoricalEventsGetWithHttpInfo
     *
     * List historical odds events (paginated)
     *
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to 'v1')
     * @param  int|null $sport_id (optional)
     * @param  int|null $league_id (optional)
     * @param  int|null $team_id Filter to events involving this team as either home or away. (optional)
     * @param  string|null $start_date Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  string|null $end_date Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalEventsGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1HistoricalEventsGetWithHttpInfo($schema_version = 'v1', $sport_id = null, $league_id = null, $team_id = null, $start_date = null, $end_date = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1HistoricalEventsGet'][0])
    {
        $request = $this->v1HistoricalEventsGetRequest($schema_version, $sport_id, $league_id, $team_id, $start_date, $end_date, $page, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1HistoricalEventsGetAsync
     *
     * List historical odds events (paginated)
     *
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to 'v1')
     * @param  int|null $sport_id (optional)
     * @param  int|null $league_id (optional)
     * @param  int|null $team_id Filter to events involving this team as either home or away. (optional)
     * @param  string|null $start_date Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  string|null $end_date Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalEventsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1HistoricalEventsGetAsync($schema_version = 'v1', $sport_id = null, $league_id = null, $team_id = null, $start_date = null, $end_date = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1HistoricalEventsGet'][0])
    {
        return $this->v1HistoricalEventsGetAsyncWithHttpInfo($schema_version, $sport_id, $league_id, $team_id, $start_date, $end_date, $page, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1HistoricalEventsGetAsyncWithHttpInfo
     *
     * List historical odds events (paginated)
     *
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to 'v1')
     * @param  int|null $sport_id (optional)
     * @param  int|null $league_id (optional)
     * @param  int|null $team_id Filter to events involving this team as either home or away. (optional)
     * @param  string|null $start_date Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  string|null $end_date Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalEventsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1HistoricalEventsGetAsyncWithHttpInfo($schema_version = 'v1', $sport_id = null, $league_id = null, $team_id = null, $start_date = null, $end_date = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1HistoricalEventsGet'][0])
    {
        $returnType = 'object';
        $request = $this->v1HistoricalEventsGetRequest($schema_version, $sport_id, $league_id, $team_id, $start_date, $end_date, $page, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1HistoricalEventsGet'
     *
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected. (optional, default to 'v1')
     * @param  int|null $sport_id (optional)
     * @param  int|null $league_id (optional)
     * @param  int|null $team_id Filter to events involving this team as either home or away. (optional)
     * @param  string|null $start_date Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  string|null $end_date Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD. (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalEventsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1HistoricalEventsGetRequest($schema_version = 'v1', $sport_id = null, $league_id = null, $team_id = null, $start_date = null, $end_date = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1HistoricalEventsGet'][0])
    {


        if ($sport_id !== null && $sport_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$sport_id" when calling HistoricalApi.v1HistoricalEventsGet, must be bigger than or equal to 1.');
        }
        
        if ($league_id !== null && $league_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$league_id" when calling HistoricalApi.v1HistoricalEventsGet, must be bigger than or equal to 1.');
        }
        
        if ($team_id !== null && $team_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$team_id" when calling HistoricalApi.v1HistoricalEventsGet, must be bigger than or equal to 1.');
        }
        


        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling HistoricalApi.v1HistoricalEventsGet, must be bigger than or equal to 1.');
        }
        
        if ($page_size !== null && $page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling HistoricalApi.v1HistoricalEventsGet, must be smaller than or equal to 100.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling HistoricalApi.v1HistoricalEventsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/v1/historical/events';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $schema_version,
            'schema_version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sport_id,
            'sport_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $league_id,
            'league_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $team_id,
            'team_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_date,
            'start_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_date,
            'end_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1HistoricalOddsEventIdExtGet
     *
     * Download a per-event historical odds file
     *
     * @param  int $event_id Canonical event identifier. (required)
     * @param  string $ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to 'v1')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalOddsEventIdExtGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse
     */
    public function v1HistoricalOddsEventIdExtGet($event_id, $ext, $schema_version = 'v1', string $contentType = self::contentTypes['v1HistoricalOddsEventIdExtGet'][0])
    {
        list($response) = $this->v1HistoricalOddsEventIdExtGetWithHttpInfo($event_id, $ext, $schema_version, $contentType);
        return $response;
    }

    /**
     * Operation v1HistoricalOddsEventIdExtGetWithHttpInfo
     *
     * Download a per-event historical odds file
     *
     * @param  int $event_id Canonical event identifier. (required)
     * @param  string $ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to 'v1')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalOddsEventIdExtGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse|\Odditt\ApiClient\Model\TrendsErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1HistoricalOddsEventIdExtGetWithHttpInfo($event_id, $ext, $schema_version = 'v1', string $contentType = self::contentTypes['v1HistoricalOddsEventIdExtGet'][0])
    {
        $request = $this->v1HistoricalOddsEventIdExtGetRequest($event_id, $ext, $schema_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
                case 502:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 502:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\TrendsErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1HistoricalOddsEventIdExtGetAsync
     *
     * Download a per-event historical odds file
     *
     * @param  int $event_id Canonical event identifier. (required)
     * @param  string $ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to 'v1')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalOddsEventIdExtGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1HistoricalOddsEventIdExtGetAsync($event_id, $ext, $schema_version = 'v1', string $contentType = self::contentTypes['v1HistoricalOddsEventIdExtGet'][0])
    {
        return $this->v1HistoricalOddsEventIdExtGetAsyncWithHttpInfo($event_id, $ext, $schema_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1HistoricalOddsEventIdExtGetAsyncWithHttpInfo
     *
     * Download a per-event historical odds file
     *
     * @param  int $event_id Canonical event identifier. (required)
     * @param  string $ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to 'v1')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalOddsEventIdExtGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1HistoricalOddsEventIdExtGetAsyncWithHttpInfo($event_id, $ext, $schema_version = 'v1', string $contentType = self::contentTypes['v1HistoricalOddsEventIdExtGet'][0])
    {
        $returnType = 'object';
        $request = $this->v1HistoricalOddsEventIdExtGetRequest($event_id, $ext, $schema_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1HistoricalOddsEventIdExtGet'
     *
     * @param  int $event_id Canonical event identifier. (required)
     * @param  string $ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;. (required)
     * @param  string|null $schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. (optional, default to 'v1')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1HistoricalOddsEventIdExtGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1HistoricalOddsEventIdExtGetRequest($event_id, $ext, $schema_version = 'v1', string $contentType = self::contentTypes['v1HistoricalOddsEventIdExtGet'][0])
    {

        // verify the required parameter 'event_id' is set
        if ($event_id === null || (is_array($event_id) && count($event_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_id when calling v1HistoricalOddsEventIdExtGet'
            );
        }
        if ($event_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$event_id" when calling HistoricalApi.v1HistoricalOddsEventIdExtGet, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'ext' is set
        if ($ext === null || (is_array($ext) && count($ext) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ext when calling v1HistoricalOddsEventIdExtGet'
            );
        }



        $resourcePath = '/v1/historical/odds/{event_id}.{ext}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $schema_version,
            'schema_version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($event_id !== null) {
            $resourcePath = str_replace(
                '{event_id}',
                ObjectSerializer::toPathValue($event_id),
                $resourcePath
            );
        }
        // path params
        if ($ext !== null) {
            $resourcePath = str_replace(
                '{ext}',
                ObjectSerializer::toPathValue($ext),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/csv', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
