<?php
/**
 * LookupsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Odditt\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Odditt\ApiClient\ApiException;
use Odditt\ApiClient\Configuration;
use Odditt\ApiClient\FormDataProcessor;
use Odditt\ApiClient\HeaderSelector;
use Odditt\ApiClient\ObjectSerializer;

/**
 * LookupsApi Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LookupsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1AffiliatesLookupsAffiliateNetworksGet' => [
            'application/json',
        ],
        'v1AffiliatesLookupsOfferCategoriesGet' => [
            'application/json',
        ],
        'v1AffiliatesLookupsOperatorJurisdictionsGet' => [
            'application/json',
        ],
        'v1AffiliatesLookupsOperatorsGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1AffiliatesLookupsAffiliateNetworksGet
     *
     * Affiliate networks
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|\Odditt\ApiClient\Model\AffiliateErrorResponse
     */
    public function v1AffiliatesLookupsAffiliateNetworksGet(string $contentType = self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'][0])
    {
        list($response) = $this->v1AffiliatesLookupsAffiliateNetworksGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation v1AffiliatesLookupsAffiliateNetworksGetWithHttpInfo
     *
     * Affiliate networks
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|\Odditt\ApiClient\Model\AffiliateErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AffiliatesLookupsAffiliateNetworksGetWithHttpInfo(string $contentType = self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'][0])
    {
        $request = $this->v1AffiliatesLookupsAffiliateNetworksGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AffiliatesLookupsAffiliateNetworksGetAsync
     *
     * Affiliate networks
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsAffiliateNetworksGetAsync(string $contentType = self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'][0])
    {
        return $this->v1AffiliatesLookupsAffiliateNetworksGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AffiliatesLookupsAffiliateNetworksGetAsyncWithHttpInfo
     *
     * Affiliate networks
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsAffiliateNetworksGetAsyncWithHttpInfo(string $contentType = self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'][0])
    {
        $returnType = 'object';
        $request = $this->v1AffiliatesLookupsAffiliateNetworksGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AffiliatesLookupsAffiliateNetworksGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AffiliatesLookupsAffiliateNetworksGetRequest(string $contentType = self::contentTypes['v1AffiliatesLookupsAffiliateNetworksGet'][0])
    {


        $resourcePath = '/v1/affiliates/lookups/affiliate-networks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AffiliatesLookupsOfferCategoriesGet
     *
     * Offer categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|\Odditt\ApiClient\Model\AffiliateErrorResponse
     */
    public function v1AffiliatesLookupsOfferCategoriesGet(string $contentType = self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'][0])
    {
        list($response) = $this->v1AffiliatesLookupsOfferCategoriesGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation v1AffiliatesLookupsOfferCategoriesGetWithHttpInfo
     *
     * Offer categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|\Odditt\ApiClient\Model\AffiliateErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AffiliatesLookupsOfferCategoriesGetWithHttpInfo(string $contentType = self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'][0])
    {
        $request = $this->v1AffiliatesLookupsOfferCategoriesGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AffiliatesLookupsOfferCategoriesGetAsync
     *
     * Offer categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsOfferCategoriesGetAsync(string $contentType = self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'][0])
    {
        return $this->v1AffiliatesLookupsOfferCategoriesGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AffiliatesLookupsOfferCategoriesGetAsyncWithHttpInfo
     *
     * Offer categories
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsOfferCategoriesGetAsyncWithHttpInfo(string $contentType = self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'][0])
    {
        $returnType = 'object';
        $request = $this->v1AffiliatesLookupsOfferCategoriesGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AffiliatesLookupsOfferCategoriesGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AffiliatesLookupsOfferCategoriesGetRequest(string $contentType = self::contentTypes['v1AffiliatesLookupsOfferCategoriesGet'][0])
    {


        $resourcePath = '/v1/affiliates/lookups/offer-categories';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AffiliatesLookupsOperatorJurisdictionsGet
     *
     * Operator jurisdictions
     *
     * @param  int|null $operator_id operator_id (optional)
     * @param  string|null $country_code country_code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|\Odditt\ApiClient\Model\AffiliateErrorResponse
     */
    public function v1AffiliatesLookupsOperatorJurisdictionsGet($operator_id = null, $country_code = null, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'][0])
    {
        list($response) = $this->v1AffiliatesLookupsOperatorJurisdictionsGetWithHttpInfo($operator_id, $country_code, $contentType);
        return $response;
    }

    /**
     * Operation v1AffiliatesLookupsOperatorJurisdictionsGetWithHttpInfo
     *
     * Operator jurisdictions
     *
     * @param  int|null $operator_id (optional)
     * @param  string|null $country_code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|\Odditt\ApiClient\Model\AffiliateErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AffiliatesLookupsOperatorJurisdictionsGetWithHttpInfo($operator_id = null, $country_code = null, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'][0])
    {
        $request = $this->v1AffiliatesLookupsOperatorJurisdictionsGetRequest($operator_id, $country_code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AffiliatesLookupsOperatorJurisdictionsGetAsync
     *
     * Operator jurisdictions
     *
     * @param  int|null $operator_id (optional)
     * @param  string|null $country_code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsOperatorJurisdictionsGetAsync($operator_id = null, $country_code = null, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'][0])
    {
        return $this->v1AffiliatesLookupsOperatorJurisdictionsGetAsyncWithHttpInfo($operator_id, $country_code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AffiliatesLookupsOperatorJurisdictionsGetAsyncWithHttpInfo
     *
     * Operator jurisdictions
     *
     * @param  int|null $operator_id (optional)
     * @param  string|null $country_code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsOperatorJurisdictionsGetAsyncWithHttpInfo($operator_id = null, $country_code = null, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'][0])
    {
        $returnType = 'object';
        $request = $this->v1AffiliatesLookupsOperatorJurisdictionsGetRequest($operator_id, $country_code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AffiliatesLookupsOperatorJurisdictionsGet'
     *
     * @param  int|null $operator_id (optional)
     * @param  string|null $country_code (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AffiliatesLookupsOperatorJurisdictionsGetRequest($operator_id = null, $country_code = null, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorJurisdictionsGet'][0])
    {


        if ($country_code !== null && strlen($country_code) > 2) {
            throw new \InvalidArgumentException('invalid length for "$country_code" when calling LookupsApi.v1AffiliatesLookupsOperatorJurisdictionsGet, must be smaller than or equal to 2.');
        }
        if ($country_code !== null && strlen($country_code) < 2) {
            throw new \InvalidArgumentException('invalid length for "$country_code" when calling LookupsApi.v1AffiliatesLookupsOperatorJurisdictionsGet, must be bigger than or equal to 2.');
        }
        

        $resourcePath = '/v1/affiliates/lookups/operator-jurisdictions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $operator_id,
            'operator_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $country_code,
            'country_code', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1AffiliatesLookupsOperatorsGet
     *
     * Operators
     *
     * @param  string|null $search search (optional)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $page_size page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorsGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object|\Odditt\ApiClient\Model\AffiliateErrorResponse
     */
    public function v1AffiliatesLookupsOperatorsGet($search = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorsGet'][0])
    {
        list($response) = $this->v1AffiliatesLookupsOperatorsGetWithHttpInfo($search, $page, $page_size, $contentType);
        return $response;
    }

    /**
     * Operation v1AffiliatesLookupsOperatorsGetWithHttpInfo
     *
     * Operators
     *
     * @param  string|null $search (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorsGet'] to see the possible values for this operation
     *
     * @throws \Odditt\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object|\Odditt\ApiClient\Model\AffiliateErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1AffiliatesLookupsOperatorsGetWithHttpInfo($search = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorsGet'][0])
    {
        $request = $this->v1AffiliatesLookupsOperatorsGetRequest($search, $page, $page_size, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Odditt\ApiClient\Model\AffiliateErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation v1AffiliatesLookupsOperatorsGetAsync
     *
     * Operators
     *
     * @param  string|null $search (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsOperatorsGetAsync($search = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorsGet'][0])
    {
        return $this->v1AffiliatesLookupsOperatorsGetAsyncWithHttpInfo($search, $page, $page_size, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1AffiliatesLookupsOperatorsGetAsyncWithHttpInfo
     *
     * Operators
     *
     * @param  string|null $search (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1AffiliatesLookupsOperatorsGetAsyncWithHttpInfo($search = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorsGet'][0])
    {
        $returnType = 'object';
        $request = $this->v1AffiliatesLookupsOperatorsGetRequest($search, $page, $page_size, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1AffiliatesLookupsOperatorsGet'
     *
     * @param  string|null $search (optional)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $page_size (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['v1AffiliatesLookupsOperatorsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1AffiliatesLookupsOperatorsGetRequest($search = null, $page = 1, $page_size = 20, string $contentType = self::contentTypes['v1AffiliatesLookupsOperatorsGet'][0])
    {

        if ($search !== null && strlen($search) > 255) {
            throw new \InvalidArgumentException('invalid length for "$search" when calling LookupsApi.v1AffiliatesLookupsOperatorsGet, must be smaller than or equal to 255.');
        }
        
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling LookupsApi.v1AffiliatesLookupsOperatorsGet, must be bigger than or equal to 1.');
        }
        
        if ($page_size !== null && $page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling LookupsApi.v1AffiliatesLookupsOperatorsGet, must be smaller than or equal to 100.');
        }
        if ($page_size !== null && $page_size < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling LookupsApi.v1AffiliatesLookupsOperatorsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/v1/affiliates/lookups/operators';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'page_size', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
