<?php
/**
 * TrendsQuoteSandboxResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Odditt\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TrendsQuoteSandboxResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Mock pricing response. Shape differs between single (1-leg) and parlay (2+ legs); parlay responses additionally carry top-level combined odds and is_combinable / parlay_failure_reason.
 * @package     Odditt\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TrendsQuoteSandboxResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TrendsQuoteSandboxResponse"
     */
    public function testTrendsQuoteSandboxResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "american_odds_value"
     */
    public function testPropertyAmericanOddsValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "button_payload"
     */
    public function testPropertyButtonPayload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "decimal_odds_value"
     */
    public function testPropertyDecimalOddsValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_betting_market_position_maps"
     */
    public function testPropertyEventBettingMarketPositionMaps()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "flow_id"
     */
    public function testPropertyFlowId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "flow_type"
     */
    public function testPropertyFlowType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fractional_odds_value"
     */
    public function testPropertyFractionalOddsValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_combinable"
     */
    public function testPropertyIsCombinable()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "odds_implied_probability"
     */
    public function testPropertyOddsImpliedProbability()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "parlay_failure_reason"
     */
    public function testPropertyParlayFailureReason()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payout_multiplier"
     */
    public function testPropertyPayoutMultiplier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
