<?php
/**
 * V1AffiliatesLinksBulkPost202ResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Odditt\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1AffiliatesLinksBulkPost202ResponseTest Class Doc Comment
 *
 * @category    Class
 * @description V1AffiliatesLinksBulkPost202Response
 * @package     Odditt\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1AffiliatesLinksBulkPost202ResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1AffiliatesLinksBulkPost202Response"
     */
    public function testV1AffiliatesLinksBulkPost202Response()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "job_id"
     */
    public function testPropertyJobId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mode"
     */
    public function testPropertyMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "poll_url"
     */
    public function testPropertyPollUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "submitted_rows"
     */
    public function testPropertySubmittedRows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
