<?php
/**
 * V1TrendsByBettingMarketPositionPostRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Odditt\ApiClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * V1TrendsByBettingMarketPositionPostRequestTest Class Doc Comment
 *
 * @category    Class
 * @description V1TrendsByBettingMarketPositionPostRequest
 * @package     Odditt\ApiClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class V1TrendsByBettingMarketPositionPostRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "V1TrendsByBettingMarketPositionPostRequest"
     */
    public function testV1TrendsByBettingMarketPositionPostRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "event_betting_market_position_ids"
     */
    public function testPropertyEventBettingMarketPositionIds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "odds_format"
     */
    public function testPropertyOddsFormat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "product_mode"
     */
    public function testPropertyProductMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "use_cartoon_images"
     */
    public function testPropertyUseCartoonImages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
