<?php
/**
 * AccountApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Odditt\ApiClient\Test\Api;

use \Odditt\ApiClient\Configuration;
use \Odditt\ApiClient\ApiException;
use \Odditt\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1AccountApiKeysGet
     *
     * List own API keys.
     *
     */
    public function testV1AccountApiKeysGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountApiKeysKeyCodeDelete
     *
     * Deactivate an API key.
     *
     */
    public function testV1AccountApiKeysKeyCodeDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountApiKeysPost
     *
     * Create a new API key.
     *
     */
    public function testV1AccountApiKeysPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountCheckEndpointDelete
     *
     * Delete the check endpoint.
     *
     */
    public function testV1AccountCheckEndpointDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountCheckEndpointGet
     *
     * Get the configured check endpoint.
     *
     */
    public function testV1AccountCheckEndpointGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountCheckEndpointPost
     *
     * Set the check endpoint (upsert).
     *
     */
    public function testV1AccountCheckEndpointPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountConfigGet
     *
     * Get own client configuration.
     *
     */
    public function testV1AccountConfigGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountSecretPost
     *
     * Create a new client secret.
     *
     */
    public function testV1AccountSecretPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountSecretsGet
     *
     * List own client secrets.
     *
     */
    public function testV1AccountSecretsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountSecretsSecretCodeDelete
     *
     * Delete a client secret.
     *
     */
    public function testV1AccountSecretsSecretCodeDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1AccountUsageGet
     *
     * Get own usage stats.
     *
     */
    public function testV1AccountUsageGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
