<?php
/**
 * OddsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Odditt\ApiClient\Test\Api;

use \Odditt\ApiClient\Configuration;
use \Odditt\ApiClient\ApiException;
use \Odditt\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OddsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OddsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1OddsUpcomingOddsByEventPost
     *
     * Get upcoming odds by event.
     *
     */
    public function testV1OddsUpcomingOddsByEventPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
