<?php
/**
 * ReferencesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Odditt\ApiClient\Test\Api;

use \Odditt\ApiClient\Configuration;
use \Odditt\ApiClient\ApiException;
use \Odditt\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReferencesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReferencesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1ReferencesBettingMarketCategoriesGet
     *
     * Get betting market categories.
     *
     */
    public function testV1ReferencesBettingMarketCategoriesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesBettingMarketPositionsGet
     *
     * Get all betting market positions.
     *
     */
    public function testV1ReferencesBettingMarketPositionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesBettingMarketsGet
     *
     * Get betting markets (paginated).
     *
     */
    public function testV1ReferencesBettingMarketsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesCountriesGet
     *
     * Get countries (paginated).
     *
     */
    public function testV1ReferencesCountriesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesEventPeriodsGet
     *
     * Get event periods.
     *
     */
    public function testV1ReferencesEventPeriodsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesLeaguesGet
     *
     * Get leagues (paginated).
     *
     */
    public function testV1ReferencesLeaguesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesOddsFormatGet
     *
     * Get odds formats (paginated).
     *
     */
    public function testV1ReferencesOddsFormatGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesOperatorsGet
     *
     * Get operators (paginated).
     *
     */
    public function testV1ReferencesOperatorsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesPlayersGet
     *
     * Get players (paginated).
     *
     */
    public function testV1ReferencesPlayersGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesSportsGet
     *
     * Get sports (paginated).
     *
     */
    public function testV1ReferencesSportsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesSubnationalRegionsGet
     *
     * Get subnational regions (paginated).
     *
     */
    public function testV1ReferencesSubnationalRegionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesTagDimensionsGet
     *
     * Get tag dimensions.
     *
     */
    public function testV1ReferencesTagDimensionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesTagTypesSearchGet
     *
     * Search tag types.
     *
     */
    public function testV1ReferencesTagTypesSearchGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesTagTypesTagTypeIdChildrenGet
     *
     * Get child tag types.
     *
     */
    public function testV1ReferencesTagTypesTagTypeIdChildrenGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1ReferencesTeamsGet
     *
     * Get teams (paginated).
     *
     */
    public function testV1ReferencesTeamsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
