<?php
/**
 * TrendsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Odditt B2B Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Odditt\ApiClient\Test\Api;

use \Odditt\ApiClient\Configuration;
use \Odditt\ApiClient\ApiException;
use \Odditt\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TrendsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Odditt\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TrendsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for v1TrendsByBettingMarketPositionPost
     *
     * Get flows by betting market position IDs.
     *
     */
    public function testV1TrendsByBettingMarketPositionPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsFlowGraphDataFactFlowIdGet
     *
     * Get fact flow graph data.
     *
     */
    public function testV1TrendsFlowGraphDataFactFlowIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsFlowTooltipFlowTypeFlowIdGet
     *
     * Get flow tooltip payload.
     *
     */
    public function testV1TrendsFlowTooltipFlowTypeFlowIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsFlowsByIdPost
     *
     * Get flows by ids.
     *
     */
    public function testV1TrendsFlowsByIdPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsFlowsPost
     *
     * Get flows (paginated).
     *
     */
    public function testV1TrendsFlowsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsFlowsQuotePost
     *
     * Quote a batch of flows against the caller's configured check endpoint.
     *
     */
    public function testV1TrendsFlowsQuotePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsFlowsQuoteSandboxPost
     *
     * Mock operator pricing endpoint — for sandbox / development use.
     *
     */
    public function testV1TrendsFlowsQuoteSandboxPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsLeaguesWithAvailableFlowsGet
     *
     * Get leagues with available flows.
     *
     */
    public function testV1TrendsLeaguesWithAvailableFlowsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsMixedFlowsPost
     *
     * Get mixed flows (paginated).
     *
     */
    public function testV1TrendsMixedFlowsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for v1TrendsWidgetEventPost
     *
     * Submit a widget telemetry event.
     *
     */
    public function testV1TrendsWidgetEventPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
